### ISSUE TITLE
update .travis.yml file for prod and staging to avoid reaching max. # of builds in GCP

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#100]
> I just spent some time looking into this app version thing and it doesn't appear to be very well documented. Travis CI has a note here: https://docs.travis-ci.com/user/deployment/google-app-engine/#version-to-deploy
> 
> ```
> Version to deploy
> 
> Either the version flag or the default option must be set. 
> If default is true, the default version will be deployed to, which will be
> http://your-project-id.appspot.com. If the version flag is set instead,
> it will deploy to http://version-dot-your-project-id.appspot.com.
> ```
> 
> Right now this flag is not set in our .travis.yml, but my guess is that the default behavior is equivalent to setting `version: default`. We can try setting it to a named version and see if subsequent deployments overwrite that version instead of creating more versions.

Thanks so much Alex for looking into this. Your solution sounds good, but wouldn't that mean that we wouldn't have previous builds to revert back to?  

Or I guess that could be handled within TravisCI and/or gitHub?  If so, then sure you can go ahead and update the .yml file for both prod and staging, thx!

p.s. no rush on this
 ***25 points***

**Comment by alexkyllo** [comment]
It took me a couple tries to get the .travis.yml format right for this (couldn't find any examples on the web) but now it will always deploy to the same app version named "prod" in GAE, so we won't have the previous versions piling up anymore.
