### ISSUE TITLE
regression tests issues to address (for upcoming 0.4.0 release)

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#101]
ok just finished the (updated) regression tests before we push all changes to production. everything checked out, except the following 2 issues:

- [ ] the following fields (URLs to videos, talks/presentations, supplemental materials, and media coverage items) are NOT being displayed properly on all article cards (EXCEPT article page, where they're displayed fine).   i'm not sure when this started happening, and it's fairly strange that i didn't notice this sooner (but i guess that's what Regression tests are for!)   NOTE: if you add/edit one of these fields ( from an author page for e.g.), it will correctly display the info (temporarily) on the article card, but if you reload the page, the info will then disappear  (which is probably WHY i haven't yet noticed this issue, because you have to reload the page before the info disappears).

- [ ] issue inviting new user: attempting to invite a new user w/ an existing author page doesn't work (i.e., clicking "SEND INVITE" doesn't do anything, no error message is surfaced; i was trying to invite stefan-schmukle via etienne.lebel.cs2@gmail.com email address ), but i can see the following error messages:
```
Failed to load resource: the server responded with a status of 500 ()
invite:1 Uncaught (in promise) SyntaxError: Unexpected token S in JSON at position 0
```

the last time i successfully invited a user from staging was Jan 2, 2020 (user: john-bargh, email address: john.barghss@gmail.com, https://curate-science-staging-2.appspot.com/admin/invitations/invitation/)

![Untitled](https://user-images.githubusercontent.com/4512335/75192225-ce020e80-5721-11ea-8672-af6324a36071.png)

**Comment by mickaobrien** [comment]
@eplebel I should be able to get started on these tomorrow. I'll keep you posted!

**Comment by eplebel** [comment]
sounds goood, thx!!

**Comment by mickaobrien** [comment]
@eplebel I've pushed a fix for the missing URLs etc., the extra data wasn't being loaded properly. Let me know if there are any other issues.

I've been digging into the invitations thing and can't quite figure it out. I don't *think* it's related to any of the changes I've made, but at the same time I can't see why it was working and now isn't. Could you post the full response you're getting for the erroring request? I want to see exactly what's causing the issue for you. I've managed to get a similar error for a few different reasons.

You can get the full response/error log by having dev tools open when you click the 'Send Invite' button, look in the 'Network' tab and click on the 'Send Invite' request (it will have a `500` next to it) and then click on the response tab in there - more details on that here: https://developers.google.com/web/tools/chrome-devtools/network/reference#response

**Comment by eplebel** [comment]
> @eplebel I've pushed a fix for the missing URLs etc., the extra data wasn't being loaded properly. Let me know if there are any other issues.

great, but i can't see it.

i'm looking into the invitation issue.

**Comment by eplebel** [comment]
ok i just re-tested it using a brand new author and invite email address (just to make sure i wouldn't run into problems), and here is the screenshot of the erroring request w/ dev tools open. please let me know if you need any other info
![Untitled](https://user-images.githubusercontent.com/4512335/75471127-c4fe8080-595f-11ea-9326-f5e8488f295c.png)

**Comment by mickaobrien** [comment]
Ah sorry, forgot to push the fix :man_facepalming: Should be there now.

If you click on the red `create/` request in the list of requests and then open the 'Response' tab and then copy the contents of that — as in this screenshot:
![image](https://user-images.githubusercontent.com/582896/75472071-e0cb4c00-598a-11ea-9dac-0cb614619230.png)

That should hopefully shed more light on the situation.

**Comment by eplebel** [comment]
ok no worries!

and sure, here's the requested info:
```
SMTPAuthenticationError at /api/invitations/create/
(535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials j14sm9360239wrn.32 - gsmtp')

Request Method: POST
Request URL: https://curate-science-staging-2.appspot.com/api/invitations/create/
Django Version: 2.1.7
Python Executable: /env/bin/python3.7
Python Version: 3.7.6
Python Path: ['/srv', '/env/bin', '/opt/python3.7/lib/python37.zip', '/opt/python3.7/lib/python3.7', '/opt/python3.7/lib/python3.7/lib-dynload', '/env/lib/python3.7/site-packages']
Server time: Thu, 27 Feb 2020 17:48:59 +0000
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.postgres',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django_extensions',
 'rest_framework',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'invitations',
 'curate.apps.CurateConfig']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'curate.middleware.no_www_middleware']
```

**Comment by eplebel** [comment]
oh i think i have a hint... i did receive a weird message saying 

Sign-in attempt was blocked  for 	curatescience@gmail.com

![image](https://user-images.githubusercontent.com/4512335/75473282-d9904800-5962-11ea-8652-b2d0dfa6b892.png)

so perhaps gmails security has been heightened since the last time i successfully invited a user from staging was Jan 2, 2020 ????

i clicked  "Check activity", and then confirmed "Yes, it was me", but then got this message:

```
Less secure app blocked
Google blocked the app you were trying to use because it doesn't meet our security standards.
Some apps and devices use less secure sign-in technology, which makes your account more vulnerable. You can turn off access for these apps, which we recommend, or turn on access if you want to use them despite the risks. Google will automatically turn this setting OFF if it's not being used.
```
with a link to [LEARN MORE](https://support.google.com/accounts?p=lsa_blocked&hl=en)

perhaps @alexkyllo has additional ideas?

**Comment by eplebel** [comment]
OK success, it's working again, i was able to invite new user, and then log in with a non-admin account, etc.. 

 Damnit, i guess it probably *is* that gmail just somehow increased their security.

**Comment by eplebel** [comment]
though still not seeeing the fix for the article details you recently comitted (https://github.com/ScienceCommons/curate_science/commit/e3b2097d571e65c96dfc1be82dfdcc4b4ddb92f0)

looks like the build hasn't yet gone through based on https://travis-ci.org/ScienceCommons/curate_science/builds

so perhaps i just have to wait

**Comment by eplebel** [comment]
oh and one last thing:

- can you change background color of miniFigureViewer to white instead of black so that it looks nicer while thumbnails load? (could consider a loading spinner like in article editor figure uploader, but just changing color is probably quicker/good enough for now)

**Comment by mickaobrien** [comment]
Cool, glad the email is working again! Probably worth moving the sending of these emails to a transactional email service like [SendGrid](https://sendgrid.com/) or [Postmark](https://postmarkapp.com/) at some stage to avoid these issues. But if it works for now, it works!

Just pushed a fix to set the background of the MiniFigureViewer to white and that kicked off a build that pulled in the article details fix as well so it should all be up now on the staging site.

**Comment by eplebel** [comment]
ok both working thx.
please go ahead and push all changes to production! (fingers crossed)

**Comment by mickaobrien** [comment]
Just pushed there, having a quick look around and no issues so far... :eyes:

Let me know if/when anything crops up!

**Comment by eplebel** [comment]
sweet, looks good so far based on preliminary testing! i'll close this for now, but will continue testing (and just realized i still need to do a few text updates, which i'll push later today, and then may ask you to merge into master; though i may be able to do it myself)
