### ISSUE TITLE
Edit author details modal window

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#11]
specs for edit author modal window:
![edit-author-details](https://user-images.githubusercontent.com/4512335/52684726-c427c600-2f79-11e9-96d8-719015d040da.png)

**Comment by onejgordon** [comment]
Do we want affiliation to be a stored datamodel & dropdown (allowing eventual filtering), or open-ended text for now?

**Comment by eplebel** [comment]
>Do we want affiliation to be a stored datamodel & dropdown (allowing eventual filtering), or open-ended text for now?

just open-ended text for now (we can implement the auto-complete/dropdown later)

**Comment by alexkyllo** [comment]
Is this linked 1:1 to the user account? If I'm an author, can I create/edit author profiles for other people? Or can I only create one author profile for myself?

**Comment by eplebel** [comment]
>Is this linked 1:1 to the user account? 

correct. in this new simplified scheme, each user will also be an author in a 1:1 relationship.

>If I'm an author, can I create/edit author profiles for other people? Or can I only create one author profile for myself? Sounds like it's the latter, just want to make sure.

correct. each user can only create/modify articles within their own author pages.

**Comment by onejgordon** [comment]
I'm seeing that currently the data model includes `first_name`, `middle_name`, `last_name`, but this form as spec'd only includes a single name field.

Should we:

1. Try to split the full name into first/last/middle (doable if we make some assumptions about how names are entered)
2. Change the data model to store name as a single field
3. Something else?

@alexkyllo @eplebel

**Comment by alexkyllo** [comment]
I missed that when I was looking over the mockups. I can just change the author name to a single field.

**Comment by eplebel** [comment]
ya probably easiest/best to just a have single-field author name for now

**Comment by alexkyllo** [comment]
Ok, in the `redo` branch, author now has one field called `name` instead of `first_name`, `middle_name`, `last_name`

**Comment by eplebel** [comment]
was going to close this but noticed two minor issues:
1. Edit button is incorrectly being displayed for non-logged in users (clicking Edit opens the Edit Author modal, though at least one can't save any changes made).

2. If a social media URL is added, then removed, the corresponding social media icon is still displayed (and clicking it does nothing)

is it OK to have these issues here, or shall i re-post them as separate issues?

**Comment by eplebel** [comment]
this is overall working, so i will close the issue for now.

i will log the following non-MVP minor issues in separate issues:

1. Edit button is incorrectly being displayed for non-logged in users (clicking Edit opens the Edit Author modal, though at least one can't save any changes made).

2. If a social media URL is added, then removed, the corresponding social media icon is still displayed (and clicking it does nothing)
