### ISSUE TITLE
author page article list/edit functionalities

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#12]
specs for author page article list and edit functionalities:
![author-page-edit-functionalities](https://user-images.githubusercontent.com/4512335/52629113-9ac05900-2eeb-11e9-9846-21156f2de1d8.png)

when creating a new author page, everything will be blank except the "Edit info" button within the "Author information" section *and* the "Add article" and "Link preexisting article" buttons.

- "Add article" button opens the "New/Edit article info" modal window with everything empty.
- "Edit article" button opens the "New/Edit article info" modal window with pre-existing info loaded.
- Clicking "Link preexisting article" will reveal the "Find preexisting article" search box (the same one as already implemented to link an original study to a replication study (https://curatescience-staging.appspot.com/new/article/8/edit)), so that an article already in the DB can be linked to a specific author page (whether that article is linked to a different author page or not).
- clicking "Unlink" will unlink that article from that author's page (leaving it linked to any other author pages; and also leaving it in the DB, even if it's not yet linked to any other author pages).
- Added/linked articles will be displayed using the HTML and [CSS](http://curatescience.org/assets/author-assets/text-stylings-author-page.css) that i used to generate the author pages of 3 prominent (open-science maverick) researchers: [lorne.campbell](http://curatescience.org/author/lorne.campbell.html) (use this one as it covers all features), [daniel.lakens](http://curatescience.org/author/daniel.lakens.html), and [julia.rohrer](http://curatescience.org/author/julia.rohrer.html) (which are actually a slightly scaled-back version of my own [etienne.lebel author page](http://curatescience.org/author/etienne.lebel.html)). the only exception being the use of proper tooltips to display badge, replication, and commentary details on hover (note that these are interactive/contain clickable content), instead of my hacky span solution. ***UPDATE FEB 25***: if this part of the UI still hasn't been implemented, please use improved labels and full-text buttons from [etienne.lebel's author page](http://curatescience.org/author/etienne.lebel.html)

- only admins will be able to delete an article, which will unlink it from all author pages and destroy it within the DB. this works because there's no use case for an author to want to delete -- rather than unlink -- an article. if an error is made (wrong title, wrong transparency URLs, even wrong DOI), then that information can be edited. hence, deleting an article should almost never need to happen, and if it does, only admins should be able to do this. (UPDATE: one rare case i just thought of for an admin to need to delete an article is for duplicate unpublished or "in press" articles given that these won't have a DOI and our initial UI won't be checking for duplicate titles (though we could implement this later)).

(eventually, we will implement "Quick add" functionalities (e.g., drag-and-drop DOI or PDF or PDF URL onto "Add article" button, which will automatically populate basic article metadata fields); we will also implement 2 ways to add *batches* of articles: "Import from Google Scholar" and "Import from ORCID ID account")

**Comment by onejgordon** [comment]
Got it, looks good.

**Comment by alexkyllo** [comment]
Does this also need "unlink article" buttons so the author can remove a link that they added by mistake?

What do you mean by "Admin only" for Add New Article? Admins have full control over the entire site and all the data in it--that's just the 3 of us right now. I don't think you would grant that to authors, would you? 

Are there some authors who will have the ability to create an author page for themselves, and link existing articles, but they're not allowed to enter new articles? 

Or by "admin" do you just mean any logged-in user?

Just trying to figure out how many levels of authorization we need. Currently in the Django app, there are 3:

- Anonymous / unauthenticated user: read-only
- Authenticated user: can create and edit (but not delete) anything except other users
- Admin: can create, edit, and delete everything including other users

**Comment by eplebel** [comment]
>Does this also need "unlink article" buttons so the author can remove a link that they added by mistake?

yes, you're right, we need an "unlink article" button. and also need a "delete article" button. i've revised the mockup accordingly.

>What do you mean by "Admin only" for Add New Article?

"Add new article" means adding a new article NOT (yet) linked to a specific author page. This functionality will only be available for admin users (like myself and perhaps another internal curator)

>can you please list out what different user roles you want, and what specific things they should be allowed to do?

i think those 3 roles are sufficient for now, with only a small modification to the "authenticated user": 
 they can delete articles linked to their author page (but they can't delete any other articles and they cannot modify any author author pages)

**Comment by alexkyllo** [comment]
If two authors have both linked the same article to their respective pages, should one of them still be able to delete the article? If so, it would also disappear from the other author's page. Or should an author only be able to delete an article when they're the only author linked to it?

**Comment by eplebel** [comment]
>If two authors have both linked the same article to their respective pages, should one of them still be able to delete the article? ... Or should an author only be able to delete an article when they're the sole author linked to it?

good catch. and yes an author should only be able to delete an article when they're the sole author linked to it? however, in the event an author tries to delete an article that has been linked to a different author page, a dialog box could at least give them the option to *unlink* it from their author page (though a user would very rarely want to do this).

so the dialog box would say:
"You cannot delete this article because a co-author has linked it to their own author page. You can, however, unlink the article from your author page." (and then display the same "Unlink" button as in the mockup and a "Cancel" button).

**Comment by alexkyllo** [comment]
That's sound logic, though starting to get a little complex--maybe we should provide just unlink first for simplicity, and implement delete later? Meanwhile, admins can delete anything, so if someone creates a bunch of garbage articles for some reason, admins can always clean it up.

**Comment by alexkyllo** [comment]
I agree, if we stick with unlink only for authors, delete for admins, that will keep the logic simpler.

**Comment by onejgordon** [comment]
@eplebel do you have a preference for what the author page URL is? From the discussion in https://github.com/ScienceCommons/curate_science/issues/14 it sounds like we don't have a separate username field besides email address, though of course the datastore will have a separate unique id. 

As such, should the url be something like `/app/authors/[numeric_db_id]`, `/app/authors/[user_email]`, or something user defined? If user defined, we'd need to make this an editable field, and prompt to populate it when a new author page is being created (by a user, or an admin).

This also has implications for the user/author lookup API.

**Comment by onejgordon** [comment]
> * Added/linked articles will be displayed using the HTML and [CSS](http://curatescience.org/assets/author-assets/text-stylings-author-page.css) that i used to generate the author pages of 3 prominent (open-science maverick) researchers

Question on this for @eplebel.

For the article list items, does the HTML & CSS need to exactly match the examples provided, or just exactly visually match? Since the webapp is in React we need to re-implement the component that creates the article list which would benefit from use of material-ui components, etc, that may have a slightly different HTML structure, but hopefully very similar visual appearance.

**Comment by alexkyllo** [comment]
There actually is a separate username field in the Django User model. I was planning to default it to the e-mail, but we could also allow the user to pick a username.

**Comment by onejgordon** [comment]
Ugly edge case, but if we allow it to be customized, a user could hypothetically choose a username that's identical to an existing (or future) CS author. May be safer to prompt creation of unique username at signup time... but that raises the question about a separate flow for admins who are creating author pages.

**Comment by alexkyllo** [comment]
One option is to add a slug field to the Author model, generate it when the Author record is created, and use that as the URL identifier (e.g. /authors/etienne-p-lebel/). It'd be totally separate from the username.

Author can have a nullable one-to-one relationship with User, so that an admin can create an Author page that no User owns (yet), but a User can only own (or "claim") one Author page.

**Comment by onejgordon** [comment]
> One option is to add a slug field to the Author model, generate it when the Author record is created, and use that as the URL identifier (e.g. /authors/etienne-p-lebel/). It'd be totally separate from the username.

This too is tricky since even full names aren't universally unique. We can handle this by checking for collision and adding an integer, but etienne-p-lebel-2 might be a little annoyed.

**Comment by eplebel** [comment]
> We can handle this by checking for collision and adding an integer, but etienne-p-lebel-2 might be a little annoyed.

ya i think this is probably the best (least suboptimal) solution (and indeed looks like the solution taken by Academia.edu and ResearchGate, e.g., https://www.researchgate.net/profile/Daniel_Lakens2, https://independent.academia.edu/CampbellLorne)

how about these workflows for a new author created:
-  BY A USER: when a new author page is being created BY A USER, the author page URL would be a hyphenated version of the user's name (e.g., "Etienne P LeBel" becomes "etienne-p-lebel"), which we'll have from the invite modal window . if non-unique, then an integer is added.
- BY AN ADMIN: when a new author page is being created BY AN ADMIN, it would first prompt for the author's name, and then a hyphenated version of the user's name would be automatically be generated (just like for a user)

**Comment by eplebel** [comment]
> For the article list items, does the HTML & CSS need to exactly match the examples provided, or just exactly visually match? Since the webapp is in React we need to re-implement the component that creates the article list which would benefit from use of material-ui components, etc, that may have a slightly different HTML structure, but hopefully very similar visual appearance.

yes that's fine as long as the article cards have near-exact visual appearance to the examples provided.

**Comment by alexkyllo** [comment]
Ok, I'll add a TODO for myself to implement that author name slug field.

**Comment by onejgordon** [comment]
@alexkyllo question related to the discussion from the last iteration about returning objects with full children vs just IDs and then firing off a second call to fetch children: how do you recommend we do this for the author page? 

I see that the AuthorSerializer returns a list of article IDs. Do I need to fetch these one by one on page load, or is there a way to fetch all article objects in a single batch? If so, which endpoint should I be using for this?

**Comment by alexkyllo** [comment]
I can add an endpoint like /author/<author_slug>/articles/ and it will return a list of all articles linked to that author. Then it'll be just 2 API calls, one to get the author and one to get all their articles.

**Comment by onejgordon** [comment]
Perfect, thanks.

**Comment by alexkyllo** [comment]
Ok, the /author/<author_slug>/articles/ endpoint is implemented in the `redo` branch.

**Comment by onejgordon** [comment]
Hi @alexkyllo, do I remember you saying something about a link/unlink API for articles, or should I be doing this operation by updating the Author.articles property at the `api/authors/<slug>/update/` endpoint?

**Comment by onejgordon** [comment]
@eplebel is 'conceptual' a new article type? How does it map to relevant transparency types (which icons show in the article list item box?)

**Comment by onejgordon** [comment]
@alexkyllo, I've noticed that the Article model stores keywords as a single space delimited string, but some of the keywords on Lorne's profile (for example) are two words. The UI seems to require us to separate keywords graphically -- how should these be handled?

**Comment by alexkyllo** [comment]
Options I can think of are:

1. keywords stays a text field, keywords are space delimited, users can make multi-word keywords by hyphenating them
2. keyword stays a text field, keywords are comma delimited, anything that doesn't have a comma between it is one keyword
3. keyword changes back to a JSON field or even becomes a separate model entity and a more complex input widget can be used.

First two options are frontend-only since you can just split the keywords field on whichever delimiter with JavaScript; third option is a database change, and kinda seems misaligned with the purpose of this rewrite which is to simplify everything.

**Comment by onejgordon** [comment]
Makes sense. @eplebel do you have a preference between 1 & 2? 2 would mean keywords can't contain commas, but this doesn't seem to me like it would be a major limitation.

**Comment by alexkyllo** [comment]
> do I remember you saying something about a link/unlink API for articles, or should I be doing this operation by updating the Author.articles property at the api/authors/<slug>/update/ endpoint?

Yes, the latter is what I was intending. Let me know if you run into any issues.

**Comment by eplebel** [comment]
> Makes sense. @eplebel do you have a preference between 1 & 2? 2 would mean keywords can't contain commas, but this doesn't seem to me like it would be a major limitation.

ya let's go with 2, which is the way i implemented it for the author pages/alpha home page (https://github.com/ScienceCommons/science-commons/blob/master/curateArticleList-rev1.R)

keywordsHTML <- function(keywords) {
  if (toString(keywords) != "NA") {
    keywords.list <- strsplit(keywords, ";")
    keywords.HTML.list=""
    for (i in 1:lengths(keywords.list)) { 
      keywords.HTML.list <- paste0(keywords.HTML.list, " <span class='mdl-chip small-chip'>
                                   <span class='mdl-chip__text small-chip-text'>", trimws(keywords.list[[1]][i]) , "</span></span>") }
    return (HTML(paste0("<div class='key-words'>", keywords.HTML.list, "</div>")))
  }
}

**Comment by eplebel** [comment]
> @eplebel is 'conceptual' a new article type? How does it map to relevant transparency types (which icons show in the article list item box?)

for the 'conceptual' and 'commentary' article types, any of the badges can apply, but these are considered "bonus" badges (hence if nothing available for it, then no "unavailable" badges are displayed). e.g., http://curatescience.org/author/etienne.lebel.html#10.1037/pspi0000106

not sure if this useful, but here's how i'm doing in my R code:
````
#5 transparency ("BONUS") badges - meaning no "unavailable badge" if no URL provided 
  else if (toString(article.type) == "conceptual" | toString(article.type) == "commentary") {
    if (toString(prereg.URL) != "NA" | toString(open.mat.URL) != "NA" | toString(open.data.URL) != "NA" | toString(open.code.URL) != "NA" 
        | toString(rs.type) != "NA") {
        transparencyComponentString = HTML(paste0("<br><div class='transparency-line'>", prereg.badge.HTML(prereg.type, prereg.URL, article.type), 
                                                  materials.badge.HTML(open.mat.URL, article.type), data.badge.HTML(open.data.URL, article.type), 
                                                  code.badge.HTML(open.code.URL, article.type), rs.badge.HTML(rs.type, disclosure.date, article.type), "</div>"))
        return(transparencyComponentString) }
    }
````

**Comment by onejgordon** [comment]
@eplebel on keywords, it looks like your script splits on semicolons rather than commas, so I assume that's your preference.

> these are considered "bonus" badges

Thanks, wasn't aware of this distinction.

**Comment by onejgordon** [comment]
@alexkyllo does the author slug logic agreed upon above (hyphen-joined, add integer as necessary) implemented server side, or is this something I should do client-side (try Author fetch by slug via API incrementing integer if needed until one that's not taken is found).

**Comment by alexkyllo** [comment]
It's server side, I used the django-autoslug package which takes care of this for us. You should not need to generate slugs nor should you have to try to guess them.

At the time a user creates an Author profile (if that user is not an admin) when you `POST /api/authors/create/` that Author will be associated to the current user--this can be done automatically server-side by assigning: `author.user = request.user`. When the new author is saved, the slug is generated and the Author object with the slug populated, will be returned in a 201 Created [response](https://github.com/ScienceCommons/curate_science/blob/82c38d024a7bb1db49cbdf2915924e2b62352b67/curate/views_api.py#L89). From then on, any time you get `/api/users/<username>/` the related Author object will be nested in the response.

**Comment by onejgordon** [comment]
OK, I'm testing this with a non-staff user and it's not yet working (returns 400), I believe because when `serializer.is_valid()` is run we haven't yet populated user. Should be an easy fix.

**Comment by alexkyllo** [comment]
400 is a client error code, it usually means you're missing a required field. Does the response payload give you any clues? If you send me a copy of the JSON payload you're posting I can tell you why it's erroring.

**Comment by onejgordon** [comment]
Yeah it's saying account is missing.

**Comment by alexkyllo** [comment]
Ok, we will need to make account a non-required field in the AuthorSerializer.

If you feel like doing it yourself right now, you can add `required=False,` as an argument to [this SlugRelatedField constructor call](https://github.com/ScienceCommons/curate_science/blob/57c7313012b020edbd7e6e0c2d2c6ded8c88c46d/curate/serializers.py#L17)

**Comment by onejgordon** [comment]
Will do, thanks

**Comment by eplebel** [comment]
> @eplebel on keywords, it looks like your script splits on semicolons rather than commas, so I assume that's your preference.

actually please split on comma (option 2), given that most often that is how the text is formatted within a pdf or article html (so faster curation)

**Comment by eplebel** [comment]
Most major issue for the author page on staging (https://curatescience-staging.appspot.com/app/author/etienne-lebel):

- clicking "Add article" button does *not* open the "New article" modal window with everything empty.

instead, it adds a "New untitled article created at xxx" article at the top of the list.  this can then be edited and subsequently saved, but this is not the right workflow.  the "New article" modal window needs to open *without* visibly adding anything to the list because the user could click "Cancel" within that window.

**Comment by onejgordon** [comment]
@eplebel, you're right. This was my initial solution based on our conversation about when article creation should occur (cf https://github.com/ScienceCommons/curate_science/issues/10#issuecomment-466131999 and following comments). 

Bringing up the dialog immediately upon creation is no problem, but if it is necessary to wait to do any creation in db until all data is entered, this still presents a challenge. Here are some thoughts & a few options that I can see, if you or @alexkyllo have other thoughts, let's discuss here:

_Issue: Uploading key figures is currently an action that requires an article to already exist in db._

1.  One option is we wait to create article until necessary, which will be either (a: user finishes filling out all data without any figures / commentaries, b: user attempts to upload an image). The problem I see with this is that we will break the user's expectation that articles don't exist until 'Save' is clicked. Users that upload a figure and then cancel may be surprised to find the article has already been added to their page.
2. Another option is we hide the image upload feature until the article has been created, but this is a hidden affordance (they only see they can upload figures after filling form, saving, then clicking edit a second time).
3. We create when form opens, and delete if user clicks cancel. This was discussed, and is not ideal since it is likely to leave unexpected orphan articles if the user exits the flow in other ways besides canceling.
4. If one-shot article creation is critical, we can re-explore the question of a single multipart form upload that accepts multiple images and form params in a single request. I think we were trying to avoid this though based on our conversation in #10.

**Comment by eplebel** [comment]
well, based on the way the DB is currently setup, it seems like the best solution would be option 3 ("We create when form opens, and delete if user clicks cancel. This was discussed, and is not ideal since it is likely to leave unexpected orphan articles if the user exits the flow in other ways besides canceling.")

the issue with orphan articles seems moot because (1) this should happen very rarely (because we'll of course warn users if they're canceling out of the window with *unsaved* text/changes; or if they're trying to close the browser window altogether), and (2) in the extremely rare case orphan articles are created, this isn't really a problem for the DB right?

**Comment by alexkyllo** [comment]
I thought we had decided on option 2, and how I pictured this working is: you open the create article modal, enter data, save it, and then the view that you're shown immediately after saving it shows you the article you just saved and has the '+' buttons for uploading key figures to the article.

Options 1 and 3 will leave orphaned data in the database, and anything that we think will happen very rarely will probably still happen often enough to cause us a headache. If you don't want your users to do something, it's best to make it impossible.

Option 4 is fine, except that it goes against the grain of the React SPA + REST API architecture and implies non-trivial rework.

**Comment by eplebel** [comment]
no (though i think this may have been a a misunderstanding on my part). a user really has to be able to create an article and add multiple figures in the *same* step because curating an article is *already* a very onerous task. adding an extra step (for technical reasons unknown to them) is simply not an option (unless of course we can't afford it, but perhaps there's a compromise solution). 

isn't option 2 a workaround for now given that we can mark orphan articles as "not-live" so they don't show up in the link to pre-existing articles selector (marking articles as "live" as previously suggested by @onejgordon ).

**Comment by onejgordon** [comment]
Yeah, I'm still thinking this is probably the right immediate strategy.

How would non-live articles appear on the author page? Hidden from public but visible to authors (so they can edit or delete them?). Do we automatically update 'live' status or ask users to mark articles 'live' when ready? If automatic, what are the criteria?

**Comment by eplebel** [comment]
> How would non-live articles appear on the author page? Hidden from public but visible to authors (so they can edit or delete them?). 

non-live articles would never appear anywhere (because they're an extreme edge case where somehow an article was never saved *and* not canceled out of).

> Do we automatically update 'live' status or ask users to mark articles 'live' when ready? If automatic, what are the criteria?

yes all articles would automatically be labeled as 'live' whenever they are saved by the user (meaning the only criteria are the required fields).

**Comment by alexkyllo** [comment]
@onejgordon to support this, do I just need to add an IsLive Boolean field to Article, which you will set when the user pressed the save button? Should I filter for IsLive in the `/api/articles/` endpoint too?

I was thinking about whether it would make sense to write some kind of a trigger or scheduled job to clean up orphaned Articles in the database. The problem is, you could open the Create Article modal, which creates an Article record, then you could leave your browser tab open for a week, or a month. Then you could finally come back to the tab and submit the form, which would update the article and mark it IsLive. Or, you could have closed the tab a month ago. I have no way to know. Because I can't tell which "orphaned" articles are actually orphaned vs just work-in-progress, they will have to stay in the database indefinitely. 

Probably not a big deal while the user base and traffic load are still small, but we should come back and fix this design before we get to the point where we have thousands of these possibly abandoned Article records in the DB.

**Comment by onejgordon** [comment]
I was thinking about this too, since I'm also concerned about the orphans in the db. It's a slightly more insidious problem then meets the eye, since currently I believe we have a db uniqueness check on title + year. If someone starts an article and enters title & year, then closes browser, and tries to create the article at a later date, they'll be prevented from doing so.

One fix may be adding isLive to the compound uniqueness constraint?

> @onejgordon to support this, do I just need to add an IsLive Boolean field to Article, which you will set when the user pressed the save button? 

This works for me.

> Should I filter for IsLive in the /api/articles/ endpoint too?

If we really don't want to show them in any UI anywhere that's fine. Might admins want to view non-live articles in their management view? I guess we can also use the django admin for this case, and just assume everything in the app UI is live. @eplebel preferences?

**Comment by alexkyllo** [comment]
I think the easiest way to get around the uniqueness constraint would be if you assign the draft article a random string as its title and then overwrite it with the actual contents of the title field after they hit the save button.

**Comment by alexkyllo** [comment]
@onejgordon is_live field has been added to the Article model. It defaults to true, so make sure to explicitly set it to false when creating a draft article.

**Comment by eplebel** [comment]
> Might admins want to view non-live articles in their management view? I guess we can also use the django admin for this case, and just assume everything in the app UI is live. @eplebel preferences?

ya it would be useful to list non-live articles in the manage article view (so that it's easier to keep track of them), thanks.

**Comment by eplebel** [comment]
this is done in a general sense.

several more specific *article list* issues are still outstanding, however, i will log these in a separate issue.
