### ISSUE TITLE
build error in staging after committing minor text tweak

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#136]
build error in staging after committing a minor text tweak (https://github.com/ScienceCommons/curate_science/commit/48631a1e2f8009f0558754227483053a280481ac#diff-3f307fcb83b37a8440d7c67012eb95b0).  i realized it could be due to the ";" string, so i replaced it with its unicode character (https://github.com/ScienceCommons/curate_science/commit/8cf58ff85ec4848958bdb59ad1933cd89c4c0dcb), as previously done elsewhere on the Home.jsx by @mickaobrien , but build error is still occurring.

details: https://travis-ci.org/github/ScienceCommons/curate_science/builds/712674394

```
Collecting MarkupSafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/python3.6.7/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-faczmcee/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-faczmcee/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-grnny6fx
         cwd: /tmp/pip-install-faczmcee/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-faczmcee/MarkupSafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command "pip install -r requirements.txt" failed and exited with 1 during .
```

i did a quick search, and did find this (https://github.com/pallets/markupsafe/issues/57) , which suggests it could be a version/compatibility issue in the MarkupSafe 1.0 library, so upgrading to 1.1.0 version perhaps might fix the issue?

**Comment by alexkyllo** [comment]
Yes, related issue on the setuptools project https://github.com/pypa/setuptools/issues/2017 says that MarkupSafe 1.0 depends on a deprecated API in setuptools. Upgrading to the latest version of MarkupSafe should fix this.

**Comment by eplebel** [comment]
thx so much for quick turn around on this!!
