### ISSUE TITLE
Update article list item component to match sample page

### ISSUE THREAD

**Issue by onejgordon** [ScienceCommons/curate_science#16]
From Etienne:

please use improved labels and full-text buttons from [etienne.lebel's author page](http://curatescience.org/author/etienne.lebel.html) (from https://github.com/ScienceCommons/curate_science/issues/12)

**Comment by onejgordon** [comment]
<img width="591" alt="screen shot 2019-02-25 at 9 53 53 am" src="https://user-images.githubusercontent.com/57584/53357688-4d78ba00-38e3-11e9-8335-6abca2afe57f.png">

**Comment by onejgordon** [comment]
Code for preprint content icons from Etienne:

```
(content.URL) {
  if ( grepl("osf",content.URL) == TRUE | grepl("psyarxiv",content.URL) == TRUE) {
    return ( "<i class='ai ai-osf ai-2x small-icon'></i>") }
  else if ( grepl("figshare",content.URL) == TRUE) {
    return ( "<i class='ai ai-figshare ai-2x small-icon'></i>") }
  else if ( grepl("ssrn",content.URL) == TRUE) {
    return ( "<img src='../logos/author-logos/sprite-icons/SSRN-logo.png' class='SSRN-logo'>") }
}
```

**Comment by eplebel** [comment]
this is done in a general sense. 

several more specific stylistic/aesthetic issues are still outstanding, however, i will log these in a separate issue.
