### ISSUE TITLE
Key figure upload and manage UI & APIs

### ISSUE THREAD

**Issue by onejgordon** [ScienceCommons/curate_science#17]
Creating a new issue for this as it's a significant component within the larger article editor dialog.

**Comment by onejgordon** [comment]
@alexkyllo it would be helpful to get a JSON object (KeyFigure) back from the `api/articles/<int:article_pk>/key_figures/upload/` endpoint upon successful creation, so we can incrementally update the form UI. Doable?

**Comment by alexkyllo** [comment]
@onejgordon this is done. now it will return a response body like this:

```json
{
    "id": 23,
    "image": "/media/key_figures/file_name.jpg",
    "height": 2304,
    "width": 2222,
    "thumb_height": 75,
    "thumb_width": 73,
    "thumbnail": "/media/key_figures/file_name_thumb.jpg"
}
```

However, Google App Engine uses a read-only filesystem so the uploads aren't working in that environment. I will need to rewrite the file upload handler to use Google Cloud Storage per this: https://cloud.google.com/python/getting-started/using-cloud-storage#handling_user_uploads

I'll let you know as soon as I get that done.

**Comment by alexkyllo** [comment]
@onejgordon Just tested in staging, the API now uploads KeyFigure image and thumbnail files to google cloud storage buckets instead of the local filesystem, and returns a stable URL with public read access.

**Comment by eplebel** [comment]
this is overall working, so i will close the issue (multiple-file uploading still not implemented, but i will log this in a separate, more minor , issue)
