### ISSUE TITLE
Make current CS collections/replications available as static pages in new app

### ISSUE THREAD

**Issue by onejgordon** [ScienceCommons/curate_science#2]
Goal is to make transition seamless for those currently depending on the data in these pages, before updated collections/replications functionality is finalized in the redesign.

**Comment by eplebel** [comment]
this seems to be working in staging (https://curatescience-staging.appspot.com/app/replications), so i'm closing the issue.
(links to replication collections are broken (e.g., https://curatescience-staging.appspot.com/sitestatic/legacy/collections/macbeth-effect.html), but i can live with this given that these collections are based on old UI prototypes.)
