### ISSUE TITLE
create new author page functionality

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#20]
https://curatescience-staging.appspot.com/app/create_author

needs to work for admins (to create new author pages) *and* for non-admin users to create their own author page.

**Comment by onejgordon** [comment]
@eplebel just tested this for admin and user, and both seemed to work (note that username is optional for admins creating new authors).

If there's an issue, could you let me know which operation you were trying to perform, and what happened?

**Comment by eplebel** [comment]
oh i guess it *does* work without inputting a user name.

i guess i can't test creating an author page for a pre-existing user (because inviting a new user still yields "Error inviting!" ), but i will mark this resolved for now. 

oh and an error should be rendered to the UI if one tries to create an author page for a user name that doesn't exist (as i was trying to do), but this is pretty low priority.

**Comment by onejgordon** [comment]
> an error should be rendered to the UI if one tries to create an author page for a user name that doesn't exist (as i was trying to do), but this is pretty low priority.

Created issue to track this: https://github.com/ScienceCommons/curate_science/issues/28
