### ISSUE TITLE
form loading/saving frontend latency and responsiveness issues

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#21]
though the server side latency issue was noticeably improved by fixing #9 , several more specific frontend latency issues still remain:

some operations still take more than ~1.5 seconds for anything to happen on screen. for example:
- clicking "Add Article" takes almost 2 seconds to open the New Article modal window; 
- linking a pre-existing article to an author page takes about ~3 seconds for anything to happen after clicking on the found article within the react-select component
- when editing an article, it takes ~1.5 second for the existing article info to load (and article information from previous article is shown immediately, which is also confusing)

hopefully your "debounce-input" strategy (as noted in your TODO list https://github.com/ScienceCommons/curate_science/issues/10#issuecomment-468971413 ; Form update performance (latency, consider https://www.npmjs.com/package/react-debounce-input)) will help.

of course i'm not expecting enterprise-level performance (given our limited budget), but i'm hoping we can achieve about a 1-second delay maximum for most operations.

also, responsive feedback is missing for most (slow) operations. for instance, it would be good to add 3 animated dots (like within the react-select component), whenever an action is executed that takes longer than 1 second (e.g., displayed within the clicked button or otherwise).
![untitled](https://user-images.githubusercontent.com/4512335/54196715-6330d680-44c2-11e9-948f-fe498a9b05fe.png)

**Comment by onejgordon** [comment]
An update to the article editor with debounced inputs using simple HTML (plus the labeled box style in the spec) rather than material-ui TextFields is on staging.

**Comment by onejgordon** [comment]
The other latencies mentioned are actually server-side. 

Confirmed ~2s for the author list API call to return. @alexkyllo do you think this is expected latency for these kinds of db ops?

<img width="698" alt="Screen Shot 2019-03-16 at 8 31 56 PM" src="https://user-images.githubusercontent.com/57584/54484803-965cc800-482a-11e9-9314-c6a32ea46dfe.png">

**Comment by alexkyllo** [comment]
Yeah that's probably about the performance we should expect given that the database server is currently a free tier VM.

**Comment by eplebel** [comment]
> Yeah that's probably about the performance we should expect given that the database server is currently a free tier VM.

if that's true, then i guess we'll have to live with this for now, but how come loading an article on production (which is running on the same free tier VM) only take about .5 seconds?? (e.g., https://curate-science-216207.appspot.com/articles/8/)

in any event, we should still add "loading dots" whenever/wherever possible so that the user knows that something is happening.

**Comment by eplebel** [comment]
> An update to the article editor with debounced inputs using simple HTML (plus the labeled box style in the spec) rather than material-ui TextFields is on staging.

thanks!

quick clarification however:  "debouncing inputs" is done to improve performance, but isn't this independent of the style used? (in other words,  why would *not* using material-ui Textfield improve performance??)

**Comment by onejgordon** [comment]
> why would not using material-ui Textfield improve performance?

Two answers to this question: one is that material-ui components come with some bloat (they're not just an input, they're a bundle of DOM elements per input, so this can have performance impacts. The larger reason I went this way, however, was that the input debouncing library I've found so far don't seem to support custom components, but rather work with native input elements instead, so I decided to style native inputs with CSS. This felt more loyal to the original designs you shared, so figured it wouldn't be an issue.

Do you prefer the material-ui TextFields? If so I can do some more digging for a debounce strategy that's compatible with them.

> adornments are now no longer displayed

Yes, this is related. Re-adding them with the native HTML inputs will take some time and it seemed non-critical to data entry so I haven't prioritized it yet. It also seemed like we were getting short on horizontal real-estate especially in that view counts grid, and I was questioning whether the cost benefit of those icons was in their favor.

**Comment by eplebel** [comment]
yes the material-ui TextFields are definitely preferred (and also for consistency across the entire website). but ya this is not currently a priority, so i will close this issue for now.

(but actually, given there's no latency issue on production, perhaps we don't need debouncing and could try putting back material-ui TextFields and adornments. though i guess we can't really test this *before* the latency issue on staging is resolved.)

**Comment by onejgordon** [comment]
It's actually quite easy to discriminate between the two kinds of latencies (server side, which we see in delays during API calls, and client side, which we see as delays when typing into form elements, and other UI changes that aren't pending API responses). The two affect UX independently, so until we can figure out debouncing of TextFields, I don't recommend bringing them back in.
