### ISSUE TITLE
missing/incomplete components

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#22]
various components still missing/incomplete (only MVP-critical issues listed):

***on article cards within article lists*** (example article lists: [LeBel](http://curatescience.org/author/etienne.lebel.html), [Campbell](http://curatescience.org/author/lorne.campbell.html)):
- [x] transparency badges below journal name (rather than below authors)
- [x] transparency badge popups (appear *above* badge; auto-close so can see popup of next/neighbor badge; display linked link icon rather than URL)
- [x] (bonus) transparency badges not being rendered for "Commentary" and "Conceptual" article types
- [x] display # of replications within replication label
- [x] replication details on Replication label hover
- [x] commentaries label (including # of commentaries)
- [x] commentaries details on Commentaries label hover
- [ ] view key figures via fancyBox plugin

***Edit Article modal window:***
- [x] replication details form inputs (see [here](https://github.com/ScienceCommons/curate_science/issues/10#issuecomment-469644654))

more minor outstanding issues will be posted in a separate "low priority" (non-MVP) issue.

**Comment by onejgordon** [comment]
@eplebel what is the URL for 'replication taxonomy' referenced in #10?

**Comment by eplebel** [comment]
great progress on these, but some remaining issues:

- for all popups (transparency badges, replication details, commentary details), the popup window must remain open so users can interact with the information within the popup (e.g., click on hyperlinks). popup only closes once mouse leaves the bounds of the popup. 

- within transparency popups, display link icons linked to URL rather than displaying URL

- for "Commentary" and "Conceptual" article types, (bonus) transparency badges still not being rendered correctly. unavailable (greyed-out) badges should not be displayed for transparencies without a URL (or endorsement in the case of reporting standards). [e.g.](http://curatescience.org/author/etienne.lebel.html#10.1037/pspi0000106)

**Comment by onejgordon** [comment]
> fancyBox plugin

Found this React port of fancybox: https://github.com/gianglevan94/react-fancybox/issues/3, but it seems to be flawed as per this issue. Is [this library](https://frontend-collective.github.io/react-image-lightbox/) an acceptable replacement?

**Comment by eplebel** [comment]
fancybox is definitely better in terms of UX and features, so is preferred.

isn't it possible to just use fancybox programatically via their api 
as per http ://fancyapps.com/fancybox/3/docs/#usage
and
https://codepen.io/fancyapps/pen/wEVbdY?editors=1010?

**Comment by onejgordon** [comment]
jquery and React don't typically play nicely together, and we're not using jq anywhere else -- recommend avoiding adding it in as a new dependency just for this. Which are the key features of fancybox you want to make sure we have? I'll see if I can find other ports of the lib or matching functionality.

**Comment by onejgordon** [comment]
> within transparency popups, display link icons linked to URL rather than displaying URL text

![Uploading Screen Shot 2019-03-15 at 9.18.30 PM.png…]()

I find the three icons in a row as an off-site link to be a confusing UX. What's the downside of showing a (perhaps truncated to save space) version of the actual URL to the user to inform them where they're headed?

**Comment by eplebel** [comment]
> I find the three icons in a row as an off-site link to be a confusing UX. What's the downside of showing a (perhaps truncated to save space) version of the actual URL to the user to inform them where they're headed?

ya that's kind of true. the downside is that we may not have enough horizontal space (for small mobile viewports) given that we'll soon be adding open content impact metrics to the right of each link (see live spec below or on [my author page](http://curatescience.org/author/etienne.lebel.html#10.1080/15298860902979166))
![Untitled](https://user-images.githubusercontent.com/4512335/54476627-d5295880-47ff-11e9-9414-29cdffc9a894.png)

but i guess if we limit the URL text to 20 characters maximum, perhaps this is doable. so we'd have the content provider icon to the left, then the URL text (20-char max), and then the external link icon, like this:
![Untitled2](https://user-images.githubusercontent.com/4512335/54476773-7c5abf80-4801-11e9-824a-7c1ee4d0cca7.png)

**Comment by eplebel** [comment]
> jquery and React don't typically play nicely together, and we're not using jq anywhere else -- recommend avoiding adding it in as a new dependency just for this. Which are the key features of fancybox you want to make sure we have? I'll see if I can find other ports of the lib or matching functionality.

main features that seem to be missing: 
1. sharing buttons (which allows user to share link to a specific figure via copying direct link or Twitter/FB; see screenshot below)
2. being able to scroll through all figures within a set, hence allowing one to view the figures of the *next* article (and ability to do this via a thumbnail grid, see screenshot below). 

the Fancybox swiping and zooming are also way smoother (compared to Lightbox) proving a much slicker and more pleasant user experience.

![Untitled33333](https://user-images.githubusercontent.com/4512335/54477202-dd849200-4805-11e9-9d7c-b202dcd04453.png)

**Comment by eplebel** [comment]
the transparency popups are now indeed clickable (thanks for this fix!). 
that said, 2 issues still remain:
1. hovering over the badge activates the popup, but then it incorrectly auto-closes after about 1 second (at which time the action buttons [Edit, Unlink, Delete] and impact metrics appear; so issue is probably related to this) 
2. hovering over contiguous badges doesn't activate the neighbor badge's popup.

these are crucial to fix, but again are not technically needed for DB seeding. so please assign this a lower priority compared to remaining outstanding issues.

**Comment by onejgordon** [comment]
> so we'd have the content provider icon to the left, then the URL text (20-char max), and then the external link icon

This sounds good to me.

[ ] Implement update to transparency off-site links.

**Comment by eplebel** [comment]
i'm closing this for now (i will log the 2 remaining issues as separate issues; i.e., media viewer and transparency popup improvements)
