### ISSUE TITLE
stylistic/aesthetic issues

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#23]
major stylistic/aesthetic issues (MVP-critical only):

***Article list***:
- [ ] proper wrapping of full-text buttons (in own floating-right div, so that article title wraps properly)
- [ ] larger full-text buttons 
- [ ] correct max-width for cards (~530px; crucial for readability of titles and abstracts)
- [ ] larger (down-arrow) expand button (should be at least 32 x 32px)
- [ ] icons within buttons should precede text (as in specs and standard practice)
- [ ] peer review information all on the same (rather than separate) line
- [ ] author_contributions, competing_interests, and funding_sources should be trimmed beyond ~85 characters (rather than 500)

***Edit Article modal window***:
- [x] narrower padding and smaller fonts (to fit more content without vertical scrolling)
- [ ] ~~narrower max-widths for most text fields (and/or overall div) for improved readability~~

more minor aesthetic issues will be posted in a separate non-MVP issue.

**Comment by onejgordon** [comment]
> narrower max-widths for most text fields (and/or overall div) for improved readability

On this point, here are some options, which do you prefer?

1. Changing the modal to be non-fullscreen so the text fields will be shorter
2. Changing the modal to a 3-column layout so text fields will be shorter
3. Setting a max width on the inputs (I'm not sure this is ideal since it will leave unused space to the right of most input rows)

Note that the inputs are responsive in that when the browser window is narrowed, they narrow proportionally.

**Comment by eplebel** [comment]
i'd say use:
- smaller inner padding for the placeholder text box (2px instead of 8px), 
- smaller inner padding for the labeled box (also 2px instead of 8px)
- smaller height for abstract input (e.g., 18px instead of 30px)
- smaller top/bottom padding for checkbox and radio buttons (4px instead of 12px)

and that should be good enough for now (applying these within Chrome inspector allowed ~90% of content to fit vertically on screen)

**Comment by onejgordon** [comment]
> smaller height for abstract input (e.g., 18px instead of 30px)

Is the ability to see more than 1 line of the abstract at a time not useful?

**Comment by eplebel** [comment]
ok thanks so much!
and no ability to see more than 1 line not needed within Edit Article modal window

**Comment by eplebel** [comment]
i'm moving remaining issues into high vs. medium priority separate issues, so i'm closing this for now
