### ISSUE TITLE
warn users if canceling out of form (or closing tab) with unsaved information

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#26]
for
- New Article modal window
- Edit article modal window
- Edit author modal window

**Comment by onejgordon** [comment]
WIP in https://github.com/ScienceCommons/curate_science/tree/feat/warn-before-close

**Comment by onejgordon** [comment]
Pushed to staging. Note that there are two cases here (for both editing of author and article):
1. Intercept tab/browser close and warn if unsaved changes
2. Intercept dialog close/cancel and warn if unsaved changes

2 should be working robustly. 1 is tricky as it depends on the `beforeunload` event, which is handled differently in different browsers. Commentary [here](https://stackoverflow.com/questions/7255649/window-onbeforeunload-not-working), and [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#Notes).

Currently in Chrome 74.0.3729.28 it seems that close can be intercepted, but modifying confirmation behavior based on state (unsaved status) does not seem to be working for type 1.

**Comment by eplebel** [comment]
ok thanks for this. this is good enough for now (we can fix the intercept on tab/browser close later, given it's a much lower priority than other outstanding items)
