### ISSUE TITLE
Show error (in UI) if admin tries to create author page with username that doesn't exist

### ISSUE THREAD

**Issue by onejgordon** [ScienceCommons/curate_science#28]
As mentioned in https://github.com/ScienceCommons/curate_science/issues/20#issuecomment-472317301

I believe an API change will be required to support this.

**Comment by alexkyllo** [comment]
The API already throws an error if you give it an account slug for a user that doesn't exist, I just tested this.

```json
POST /api/authors/create/ HTTP/1.1

Host: localhost:8000
Content-Type: application/json
{
    "account": "foo-bar",
    "orcid": "",
    "name": "Foo Bar",
    "position_title": "",
    "affiliations": "",
    "profile_urls": null,
    "articles": []
}
```

```json

HTTP 400 Bad Request


Allow: POST, OPTIONS, GET
Content-Type: application/json
Vary: Accept

{
    "account": [
        "Object with username=foo-bar does not exist."
    ]
}
```

**Comment by eplebel** [comment]
so it works server-side, but i'm reopening this because it's still an issue in the UI

**Comment by onejgordon** [comment]
This is fixed and will appear on staging shortly.

Related question: it's not possible to get to the create author page for admins that have their own author page (the link just changes to 'my author page' as per the spec). Should 'create author' be a link that always appears for admins?

**Comment by eplebel** [comment]
> This is fixed and will appear on staging shortly.
> 
> Related question: it's not possible to get to the create author page for admins that have their own author page (the link just changes to 'my author page' as per the spec). Should 'create author' be a link that always appears for admins?
yes

**Comment by eplebel** [comment]
an error message is now correctly being issued.
however, if one then deletes the user name and clicks "Create", the system incorrectly issues this error: "This field may not be null." 
(but reloading the page and just entering a full name *does* correctly create an author page).
