### ISSUE TITLE
"In press" checkmark no longer working

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#30]
saving an article as "In press" incorrectly saves it as being published in default (2019) or inputted year. 

if you edit the article and delete the default 2019 (or any other entered year) and try to save, nothing happens (presumably because an error is thrown).

i believe this previously worked (but can't remember when).

steps.
1. create a new article with title, authors, and click "In press"
2. save article
Notice it says 2019
3. now click Edit article
4. remove 2019 and click Save
Notice nothing happens

**Comment by alexkyllo** [comment]
To rule out the possibility of this being a backend issue, I checked that the year field is nullable in the backend and it's not being defaulted to 2019 or anything. Meanwhile, in_press is a boolean field that defaults to false. So I'm pretty sure this on the JavaScript side.

**Comment by eplebel** [comment]
thanks @alexkyllo !

**Comment by onejgordon** [comment]
Fix on staging shortly
