### ISSUE TITLE
articles not correctly being linked to an author

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#31]
it appears that when creating new articles or linking them to an author, some of the articles do not get correctly linked to the author.

scenario 1:
- i was adding new articles to [lorne campbell's production author page](https://curate-science-216207.appspot.com/app/author/lorne-campbell) via "Add article".
- as i was adding them, they were correctly appearing at the top of his author page
- after having added all of his 22 articles, i loaded his author page in Firefox to make sure that i could view all of his articles publicly (without being logged in).

only 13 articles were listed.

but when i checked the [admin page](https://curate-science-216207.appspot.com/app/admin/manage), all 22 articles are in fact listed.

scenario 2:
- to see if i could reproduce this, i went to [my author page](https://curate-science-216207.appspot.com/app/author/etienne-lebel), and linked 11 articles i had just created on top of the 4 articles already on my author page.
- again, as i was individually linking them, they correctly appeared at the top of my author page
- i then went to Firefox to load my author page, 

and only 5 articles were listed.

i went back and refreshed my author page (within my logged-in session), and sure enough now only (the same) 5 articles appeared.

hence, it appears articles sometimes aren't being correctly linked to an author (when being created or linked), but i have no idea why it's only happening *sometimes*.

this is kind of a show stopper, and needs to be fixed for me to be able to continue seeding the production DB.

**UPDATE:** the problem seems to only emerge when creating/linking articles *in succession*. if i link an article, and then refresh the page, and then link another article, and then refresh the page, the articles do seem to be linked correctly. however, if i try to link articles *in succession* without refreshing the page in between, then only *some* get linked correctly.

**Comment by alexkyllo** [comment]
Before I investigate this as a backend issue, can @onejgordon please confirm that the front end is correctly submitting the author id # in the `authors` field on the article object when it does the `POST /api/articles/create/` and `POST '/api/articles/<int:pk>/update/` for these scenarios?

**Comment by onejgordon** [comment]
Confirmed we're POSTing 'authors': [author.id] on initial create (before any data is entered). 

For the update (when user clicks save), I'm sending a PATCH with the entire article object, including any updates. Confirmed this includes the `authors` field appropriately.

That said, I do believe the issue is a frontend one, possibly that involves use of the unlink/link buttons after creating new articles on an author's page. 

@alexkyllo I'm currently performing link/unlink by PATCHing an author object with an updated `articles` array. I believe that this array isn't staying in sync with the server, e.g. when new articles are created, and so a link/unlink operation after new articles are created (but without a page refresh) result in losing some of the linked articles when the author PATCH occurs. 

I can resolve this by more carefully managing the state of the `articles` array, but I wonder if there's a more robust way to do linking/unlinking via the API? If we keep this logic client side we'll always have the potential scenario where an author page is being edited in two browsers (perhaps by same or different users), and a link or unlink loses some of the history of recently linked articles in the other client.

**Comment by alexkyllo** [comment]
To clarify one thing: When @eplebel is visiting the author page of an author other than himself, clicks into the Create Article modal and creates a new article, the app will submit the author_id of the author whose page he was visiting, in the authors array, is that correct?

As far as managing the state, it's still possible to implement separate API endpoints specifically for creating and deleting author-article relationships, if you think that would help. 

How would you want that to work? Something like this?

Link:
```json
POST /authors/<author_slug>/articles/add/
{
  "article": 1
}
```
Unlink:
```json
DELETE /authors/<author_slug>/articles/<int:article_id>/
```

**Comment by onejgordon** [comment]
> To clarify one thing: When @eplebel is visiting the author page of an author other than himself, clicks into the Create Article modal and creates a new article, the app will submit the author_id of the author whose page he was visiting, in the authors array, is that correct?

Correct.

For the link/unlink API, I'm fine with anything you think is reasonably intuitive. We can even do it with a single call, if easier:

```
POST /authors/<author_slug>/articles/link_change/
{
  "article": 1,
  "action": "unlink" // (or "link")
}
```

**Comment by alexkyllo** [comment]
Is there a potential use case for linking/unlinking multiple articles from the same author at the same time?

If so, I might suggest this:

```json
POST /authors/<author_slug>/articles/linkage/
[
  {
    "article": 1,
    "action": "unlink"
  },
  {
    "article": 2,
    "action": "link"
  }
]
```

**Comment by onejgordon** [comment]
I suppose if the UI changed at any point to allow the selection of multiple articles during a link or unlink operation, having a batch API could be handy. If it's not much extra work, sounds good. In the current UI, however, we'll definitely only be doing one at a time.

**Comment by alexkyllo** [comment]
Ok. I think this will be pretty easy, I'll try and write this endpoint, hopefully tonight. And since it's a two-state thing it's probably best to make it a boolean.

Unlinking article 1 from <author_slug> and linking article 2 to <author_slug> at the same time:

```json
POST /authors/<author_slug>/articles/linkage/
[
  {
    "article": 1,
    "linked": false
  },
  {
    "article": 2,
    "linked": true
  }
]
```

**Comment by alexkyllo** [comment]
@onejgordon this is done in staging and being deployed now.

It works as described above, only thing I changed is that it will 400 Bad Request on any nonexistent article_id (because that was easier to implement).

Here's an example request that worked on my local:

```json
POST /api/authors/etienne-lebel/articles/linkage/
HTTP 200 OK
Allow: POST, GET, OPTIONS
Content-Type: application/json
Vary: Accept

[
    {
        "article": 1,
        "linked": false
    },
    {
        "article": 2,
        "linked": true
    }
]
```

**Comment by onejgordon** [comment]
Looks like this is working. Just pushed the UI update to staging.

**Comment by eplebel** [comment]
ok just finished testing this on staging and it does seem to be working  (i created 10 new articles in succession and then loaded the author page in a different tab and they were all there; i then unlinked them all in succession, and they all were successfully unlinked; i then re-linked them all and they were all successfully re-linked; i also linked them all to a different author page and they all were successfully linked.

that said, i did discover what seems to be a parallel bug when *DELETING* articles, but will log this under a different issue. (deleting two articles in succession deletes each successfully, but somehow the 1st article deleted then incorrectly re-appears within the article list; pressing delete then doesn't do anything because it's already been deleted, and if page is reloaded the article doesn't appear)

and actually, i'm hoping you can try to think of other potential ways that this kind of issue ("...array isn't staying in sync with the server...") may be causing other problems i haven't yet come across, thanks.
