### ISSUE TITLE
crucial article list stylistic issues (high priority)

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#36]
high priority article list stylistic issues to be fixed for MVP (early beta testers):

- [x] icons within buttons should precede text (as in specs and standard practice)
- [x] proper wrapping of full-text buttons (in own floating-right div, so that article title wraps properly)
- [x] correct max-width for cards (~530px; crucial for readability of titles and abstracts)
- [x] larger full-text buttons 

moved from #23

**Comment by onejgordon** [comment]
> larger full-text buttons

Which are the full-text buttons?

**Comment by eplebel** [comment]
the buttons to the full-text links (PDF, HTML, preprints). please set font-size for these to 16px, and increase content provider icon to 15 x 15px (instead of 10 x 10), like so:
![Untitled](https://user-images.githubusercontent.com/4512335/54738938-8c362300-4bb6-11e9-8c24-0aa3d50e4ebe.png)

also re: proper wrapping of article title/full-text buttons, looks like you need to:
-remove "float: left" from ArticleType span
-remove "clear: both" from ArticleLI-title-297 (and decrease padding-top from 10px to 5px)

**Comment by onejgordon** [comment]
FYI still working on some UI issues with this narrower style, button wrapping, and edit buttons now overlapping 'more' button, as seen here.

<img width="543" alt="Screen Shot 2019-03-22 at 2 11 39 PM" src="https://user-images.githubusercontent.com/57584/54853248-87ec3180-4cac-11e9-90a0-1115a22ed833.png">

**Comment by eplebel** [comment]
ok great, thanks for the update!

actually, i'm not seeing the full-text button wrapping issue on my end, in case that helps.

finally, now that i'm seeing these article list changes, could you please make these additional minor tweaks:

authorpage card column
- increase max-width to 650px (up from 530px;  updating the Author-Page-cardColumn-149 to 530px results in the card itself being only 506px; but in the context of the different look/style of the page, a wider card of 626px seems more readable/legible)

abstract text
- increase font size to 12px (up from 11px)  (11px is the correct abstract font size in the specs, but it appears way smaller for some reason. i've seen sometimes a "font-size:.75rem" is applied to certain text fields, so perhaps it's due to this.)

article title
- decrease font-size to 18px (down from 19px)
- increase line-height to 20px (up from 19px)


finally, please horizontally center the navbar/topbar for all pages (e.g., by setting max-width 1000px, except for the [replication page](https://curatescience-staging.appspot.com/app/replications))

(for the edit article dialog, please add a max-width of 1100px , which is the narrowest width before the "In press" checkbox drops down and causes an extra row.)

**Comment by onejgordon** [comment]
These changes should be visible on staging.

> please horizontally center the navbar/topbar for all pages (e.g., by setting max-width 1000px, except for the replication page)

I'm not sure I understand what horizontal centering means in this case. The sitename, logo?

> for the edit article dialog, please add a max-width of 1100px 

min-width right, if goal is to keep in-press on its own row regardless of browser window width?

**Comment by eplebel** [comment]
that's awesome, thanks for all those updates!

> I'm not sure I understand what horizontal centering means in this case. The sitename, logo?

i mean horizontally center the navbar so that its width is not 100% (which looks terrible on large displays), like so:

![Untitled](https://user-images.githubusercontent.com/4512335/54981749-65f2f780-4fa9-11e9-9769-be7869961b30.png)

> min-width right, if goal is to keep in-press on its own row regardless of browser window width?

yes i guess, but again constrain it so that its width is not 100% (which is very difficult to read on large displays). so perhaps just fix the width to be 1100px, and again centering horizontally (as just explained for the navbar)
