### ISSUE TITLE
final minor tweaks to Edit Article page (before inviting 3 early beta testers)

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#44]
in the order that they appear:

- [x] for AUTHORS input box, update placeholder text to "e.g., SS Smith, JJ Jones, & KK Pratt"

for REPLICATION input boxes: 
- [x] for NUMBER OF REPS input box, remove the "2" placeholder text 
- [x] for ORIGINAL STUDY input box, update placeholder text to "e.g., SS Smith et al. (1989) Study 2"
- [x] for TARGET EFFECT(S) input box, update place holder text to "e.g., playboy effect"

- [x] for all 6 impact metric input boxes, remove the "2" placeholder text 
- [x] for ACTION EDITOR input box, update placeholder text to "e.g., SS Smith"
- [x] for PEER REVIEWERS input box, update placeholder text to "e.g., SS Smith, Anonymous reviewer 2 (separate using ',')"
- [x] for OPEN PEER REVIEWER URL, update placeholder text to "http://..." (like all the other ones)

for commentaries:
- [x] update button text to "ADD COMMENTARY" (instead of "ADD ADDITIONAL COMMENTARY").  original specs had "ADDITIONAL" because AUTHORS/PUBLICATION YEAR and COMMENTARY URL input boxes for a 1st commentary were displayed by default (hiding these until "ADD COMMENTARY" is clicked i guess is OK given that it declutters page a bit).
- [x] for AUTHORS/PUBLICATION YEAR input box, update placeholder text to "e.g., Smith & Smith (2019)"
- [x] for "COMMENTARY URL" input box, update placeholder text to "http://..." (like all the other ones)

**Comment by onejgordon** [comment]
Since we're looking at placeholder text, I wonder if you'd consider changing a few of the dummy author names to be less anglo? Seems like a small opportunity for inclusivity.

**Comment by eplebel** [comment]
thanks for quick turn around on this!
