### ISSUE TITLE
article added by admin on an author page incorrectly becomes linked to admin's own author page

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#45]
steps:
1. logged in as an admin user, add an article to an author page (other than one's own)
2. go to your own author page

notice how the article just added (on a different author page) now incorrectly appears on one's own author page (presumably because it has been incorrectly linked to it).

i'm not sure how long this has been an issue, because i only yesterday managed to link an author page to my admin account (etienne.lebel@gmail.com), but it definitely wasn't happening before i'd associated an author page to my admin account. 

(but it's kind of a crucial bug given that i need to curate several additional author pages and don't want all of these articles to become incorrectly linked to my author page).

**Comment by onejgordon** [comment]
There are only two places in the UI that we do article creation: the author page, and the admin manage page. 

In the first, we're already passing `authors: [author.id]` to the create endpoint, and in the second, we pass an empty array (assumption is the article with later be linked to an author page).

So, I've deleted 231 & 233 as suggested, and things seem to be working as designed again. Pushing to staging now.

**Comment by eplebel** [comment]
great, this seems to be fixed (and i did some regression UI tests for related actions for both admin and non-admin user and everything else still seems to be working).

thanks to both of you for a very quick turn around on this!

**Comment by eplebel** [comment]
@onejgordon so you can go ahead and push this fix to master branch, thanks

**Comment by onejgordon** [comment]
OK just pushed staging > master
