### ISSUE TITLE
non-admin users can edit and delete other authors' articles

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#48]
this actually involves 3 different problems (each of which used to work very recently):
1. non-admin users should not be allowed to delete *anyone's articles*, including their own 
2. non-admin users should not be allowed to edit other authors' articles
3. non-logged in users shouldn't see the Edit, Unlink, & Delete action buttons on card hover

i don't think these are due to a transition issue (related to user/author model changes), though i'm not 100% sure on this (but perhaps some of these may have started once [card actions were moved to outside of card](https://github.com/ScienceCommons/curate_science/commit/648703f8024c4d9bd46ac38070cc5558dbedf893)?)

**Comment by onejgordon** [comment]
The button visibility issue is a result of my change to button position which broke the visibility logic in the UI. Should be fixed shortly on staging.

If the APIs are working as designed it could be this UI issue is the only thing to be resolved.

**Comment by eplebel** [comment]
ok that fixed all issues, thanks for quick turn around on this! (please push to master branch whenever you get a chance)
