### ISSUE TITLE
adding article with prereg URL w/out specifying prereg type breaks author page

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#49]
steps:
1. add new article (add title & authors)
2. enter URL for prereg protocol URL input box, and click Save

notice author page doesn't load and following error is given:

`Uncaught TypeError: Cannot read property 'label_detail' of undefined
    at TransparencyBadge.render_feature (webpack:///./src/components/TransparencyBadge.jsx?:144)`

solution: once the "Prereg protocol URL" input box becomes non-empty, automatically select the first radio button ("Preregistered study design + analysis").

(given that this will be the correct prereg type in >95% of cases, and so solves the problem *and* increases curation efficiency!)

**Comment by onejgordon** [comment]
This should be fixed on staging.
