### ISSUE TITLE
homepage improvements - details

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#54]
display server article list & filtering/sorting as per this mockup:
(_no data model changes required for this issue_)
![HOMEPAGE-may-2019](https://user-images.githubusercontent.com/4512335/57127846-f0412f00-6d91-11e9-89f6-18b6cc8dadb2.png)

DETAILS:
*Filtering:*
* by default (upon page load), the open materials, open data, and open code filters are applied (i.e., only articles w/ open materials, data, & code are displayed)
* clicking filter button reveals the filter component
   * clicking "Clear All Filters" clears all filters (and then user would click "APPLY")
   * clicking "APPLY" applies filters, closes filter component, & updates article list (w/out re-loading the page)
       * each applied filter then appears as closeable chips at the top of the article list (on its own "filter row" to the right of the text "Filters:")
       * when a closeable chip is closed, the article list is updated (in the future we could add a "RESET" button to the right of all closeable chips, so that all closeable chips can be cleared at once (without having to re-open the filter component; like what is implemented at [newegg.com](https://www.newegg.com/global/be-en/Product/ProductList.aspx?Submit=ENE&IsNodeId=1&Description=logitech%20k120&N=1065528985%201065685472))
    * when many filters are applied, closeable chips overflow onto a new row
    * if no filters are applied, then the entire filters "row" including the text "Filters:") is hidden

*Sorting:*
* default sort is "Newest first" (newest in terms of creation date)
* clicking "SORT BY" reveals "Newest first" (selected) and "Impact". If "Impact" is clicked, this sorts the article list by articles with most impact first (impact = total # of citations, downloads, and views across all full-text options (PDF, HTML, and Preprint); later, a weighted score will be used giving more weight to citations > downloads > views (e.g., citations = 2 x downloads = 2 x views))

*Load more:* 
* loads 10 more articles (according to current filters), appended to current list (i.e., without reloading entire list)

Articles displayed using normal article card component, with exception that "Added: January 1, 2019 ["created" article field] is displayed in the bottom-right corner of the card (see mockup above).

**Comment by mickaobrien** [comment]
@eplebel Do you want the Link/Unlink button to appear beside an article on hover in the homepage view? If so do you want to allow users to link articles to themselves or just unlink existing articles?

**Comment by eplebel** [comment]
good question.  yes please also include a Link/Unlink button (in addition to Edit and Delete buttons for users with proper permissions) to appear to the right of an article card on hover in the homepage view. (i guess using the link/unlink actions as already implemented on the author page; in other words, unlink button appears if an article is already linked to a user's author page; link button appears if it isn't already linked to a user's author page.)

**Comment by eplebel** [comment]
*final outstanding issues for contract#1*:
- [ ] after modifying filters, links to articles do not work (e.g., https://curatescience.org/app/#10.1186/s12966-019-0826-1 doesn't correctly link to "Plate size and food consumption: A pre-registered experimental study in a general population sample", which is the first article at the top after clearing all filters (same issue occurs on the search results page, eg: https://curate-science-staging-2.appspot.com/app/search?q=lebel#10.1177/0956797613486983); maybe a simple solution for linking to homepage (and search results page) article list articles is to just link to an article card's article page? (author page article card links work fine, so no need to modify these).

**Comment by eplebel** [comment]
ok this final minor issue is lower priority, so we can punt on this one too. i've now closed this issue.
