### ISSUE TITLE
search & search results page - details

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#55]
search & search results page details as per this mockup:
(_no data model changes required for this issue_)
![search-results-page](https://user-images.githubusercontent.com/4512335/57130925-5d0cf700-6d9b-11e9-95f3-f14ac270cd1d.png)

**search results:**
* articles and authors appear in the search results list (search/matching based on article title, author_list, and authors)
   * authors are displayed on their own "card" with a generic person icon ([material design "person"](https://material.io/tools/icons/static/icons/baseline-person-24px.svg)), name, affiliation, and # of articles linked to their author page (name is bold, affiliation is italicized, and # of articles is secondary grey #999999)
   * clicking anywhere on author card brings user to respective author page
* FILTER & SORT BY buttons work exactly as on homepage (including displaying applied filters as a list of closeable chips in its own row just below the search results/FILTER/SORT BY row)
* SHOW MORE reveals 10 more results (exactly as on homepage)
* if no results, display "No results found. Browse recently added articles." (with 'Browse' hyperlinked to homepage)

**search box/autocomplete component:**
* autocomplete search box (similar to search box within the article selector (accessed via clicking LINK EXISTING ARTICLE button) on author page, [example](https://curate-science-staging-2.appspot.com/app/author/lorne-campbell))
   * autocomplete lists any matching articles and authors based on entered search text as per mockup above:
       * articles: Article title and authors/publication year (same colors as on article card)
       * authors: person icon, author name, and affiliation (similar to search results "author card", but with smaller "person icon" and without # of articles)
 (clicking an item within the list brings the user to the respective article or author page)

**Comment by mickaobrien** [comment]
@eplebel Do you want the article cards in the search results to have the Edit/Link/Delete actions?

**Comment by eplebel** [comment]
> @eplebel Do you want the article cards in the search results to have the Edit/Link/Delete actions?

ya that's fine for now

**Comment by mickaobrien** [comment]
@eplebel Cool, thanks. And do you want the article cards to be expandable as well? Or should clicking on them go directly to the full article page?

**Comment by eplebel** [comment]
yes article cards expandable , and clicking on *article title* should bring user to full article detail page

**Comment by mickaobrien** [comment]
Should clicking on the article title go to the article page for all cards e.g. on the home page or the author page?

**Comment by eplebel** [comment]
yes

**Comment by eplebel** [comment]
looking good, but can you add search icon within search box so that user can go to search results page for a specific search: that is, typing "lebel" + ENTER (or clicking search icon) will bring user to https://curate-science-staging-2.appspot.com/app/search?q=lebel

(while of course keeping existing auto-complete functionality)

**Comment by mickaobrien** [comment]
@eplebel Will do!

**Comment by eplebel** [comment]
*final outstanding issues for contract#1*:
- [ ] plug in search results page functionality (& add search icon within search box) so that user can go to search results page for a specific search: eg typing "lebel" + ENTER (or clicking search icon) will bring user to https://curate-science-staging-2.appspot.com/app/search?q=lebel (as mentioned [above](https://github.com/ScienceCommons/curate_science/issues/55#issuecomment-521411596)) (while of course keeping existing auto-complete functionality)
- [ ] make searchbox autocomplete component at least 2x wider (to improve readability, especially for long article titles and/or long author lists )
   - [ ] HOME and END keys don't work within searchbox (eg type "lebel", then hit HOME, notice how nothing happens, which prevents quick clearing/deletion of keyword; if this isn't an easy fix, we can postpone).
- [ ] filtering/sorting of articles is not yet working (though this may just have been temporarily left out)
- [ ] when filtering/sorting, duplicate authors appear in the search results list (but perhaps this will be resolved once filtering/sorting is fixed/implemented (point above))

**Comment by mickaobrien** [comment]
@eplebel The HOME and END key logic is a bit tricky at the moment. The library used for this component (and the article selector autocomplete) is a bit weird, the focus is on the dropdown rather than the input so the HOME and END keys work to move up and down the list of suggestion but not within the input. I don't think there's any way around this for the moment (there is a relate [PR](https://github.com/JedWatson/react-select/pull/3484) that might help eventually). There were a few issues with this for the basic search functionality as well i.e. going to the search results page on pressing enter. Ultimately I think this library should be replaced with something more appropriate, but that's maybe a job for another day.

The filters and sorting should work now. Let me know if there are any duplicates showing up still, I found one reason but I'm not sure it covers everything.

**Comment by eplebel** [comment]
ok we'll just punt on this for now (thanks for all the info.... i didn't realize the pre-existing implementation of that component was that unorthodox, definitely something we'll have to fix later). 

and yes the filters and sorting are working, and i haven't seen any duplicates, so i'm marking this page as done!

**Comment by eplebel** [comment]
shoot, just noticed this issue whereby figures, videos, talks, supp materials, and news coverage items are missing from article cards on search results page (but are showing correctly on homepage recent list and author page)

see screenshot below showing the same article with missing stuff on the search results page (left), and with all stuff on the homepage recent list (right):
![Untitled](https://user-images.githubusercontent.com/4512335/64602124-77e11f00-d3be-11e9-9736-e4e9c40d5469.png)

**Comment by mickaobrien** [comment]
Should be fixed in [this commit](https://github.com/ScienceCommons/curate_science/commit/689819fb1a1404af2b75f90275a6b2bffedff619).
