### ISSUE TITLE
article detail page - details

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#56]
very simple article detail page as per this mockup:
(_no data model changes required for this issue_)
![article-detail-page](https://user-images.githubusercontent.com/4512335/58652231-18fd0b80-82e1-11e9-9cba-01889e484b7b.png)

it basically just displays a normal article card (w/out card), with the following minor changes:
* it's displayed in its expanded state by default/upon page load
* it cannot be collapsed
* abstract text is not-trimmed (& cannot be minified)

the card will have normal actions on hover, including the link icon on the left and EDIT, LINK/UNLINK, & DELETE buttons on the right (for users with proper permissions). That is:
- EDIT & DELETE buttons always displayed for admins; 
- for non-admins, EDIT button only for authors who have linked article to their author page; 
- UNLINK button appears only if an article is already linked to a user's author page; 
- LINK button appears only if it is NOT already linked to a user's author page.

(and later (in batch # 2 features), embedabble content will be displayed in a full-mode side panel; see [Live demo](https://etiennelebel.com/author/etienne.lebel-sidePanel.html))

**Comment by mickaobrien** [comment]
@eplebel I just pushed [a commit](https://github.com/ScienceCommons/curate_science/commit/da26112c9c2a4b0e8198e75182f801d8d19caebd) for this, you can see an example on the staging site here: https://curate-science-staging-2.appspot.com/app/article/320

**Comment by eplebel** [comment]
wow, this is also looking very good. awesome job here!
i think you've covered all the requirements, i was not able to find any bugs/deviations (i even tested a non-admin user to maker sure they can only edit articles linked to their author page, and that also seems to be working as expected).

the only tiny tiny issue is that the loading spinner for the article list on the author page now seems to be missing (for example, compare https://curate-science-staging-2.appspot.com/app/author/etienne-lebel to author page article list on production: https://curatescience.org/app/author/etienne-p-lebel; loading spinner for author information still appears correctly).


really looking forward to seeing search/search results page! (and once those are working, we can then link article titles to their respective article detail pages, on the homepage and author pages).

**Comment by eplebel** [comment]
*outstanding contract#1 issues*:
- [ ] place article page content inside a paper card (same style, padding, etc. as article list article card), like so:
![article-page-card](https://user-images.githubusercontent.com/4512335/64103917-7fc41200-cd73-11e9-8729-a2647b3f3fba.png)
