### ISSUE TITLE
aesthetics/minor tweaks

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#58]
- new aesthetic article card tweaks:
  - full-text links improvements (see mockup below for precise look):
    - lower case text
    - update "ArticleContentLink" class to "padding: 2px 4px;" and no border
    - update content provider icon style to: "vertical-align:middle; margin-right:0px;"
    - add external link icon:
`<span class="material-icons MuiIcon-root-266 MuiIcon-fontSizeInherit-272" aria-hidden="true" style="margin-bottom: -2px;">open_in_new</span>`
    - update "ArticleFullTextLinks" div style to "margin-top: 0px;margin-right: -4px" so links line up with article title
![tweaks1b](https://user-images.githubusercontent.com/4512335/58659748-c6781b00-82f1-11e9-9d9f-18e8ab815cbb.png)

  - use DOI icon instead of displaying DOI text: use DOI icon from [academicon](https://jpswalsh.github.io/academicons/) with following title: "Go to journal publisher's website (opens in new window)"
`<i class="ai ai-doi ai-2x" style="vertical-align: bottom; margin-left: 3px;font-size:1.5em"></i>`
![tweaks2](https://user-images.githubusercontent.com/4512335/58657783-0688cf00-82ed-11e9-9557-92d6f3560679.png)

  - update article type, RR, and commentaries label style padding to: "padding: 1px 4px" (from padding: 2px 7px). and for commentaries label ONLY, update line-height to 1.5 (so that ALL labels look the same)
![tweaks3](https://user-images.githubusercontent.com/4512335/58658422-7481c600-82ee-11e9-91cf-7daffb7ae75f.png)
  - update author_list line-height to "line-height:1.24" (from 1.5)

  - increase size of citation icon: "font-size:18px; vertical-align:-5px"
![tweaks5](https://user-images.githubusercontent.com/4512335/58658691-0be71900-82ef-11e9-9cd9-0ece347d91e3.png)

- abstract trimming adjustment: trim after 550 characters (instead of 500), so that the "... More" appears at the end of the line

- add BETA to the right of "Curate Science (beta)")
`<sup><span style="font-size:9px;margin-left:1px;">BETA</span></sup>`
![beta-superscript](https://user-images.githubusercontent.com/4512335/58655734-cb849c80-82e8-11e9-96c6-8a659c86ee33.png)

- fix/update unavailable badge titles (to be more charitable):
  - Prereg: "Preregistration information is not (yet) available"
  - Materials: "Open/public study materials information is not (yet) available"
  - Data: "Open/public data information is not (yet) available"
  - Code: "Open/public code information is not (yet) available"
  - Reporting standards: "Reporting standards compliance information is not (yet) available"

**Comment by eplebel** [comment]
tweaks so far look great!

one minor thing i noticed for the badges: they are still not all the same; the Commentaries badge is slightly taller (19.2 instead of 17.6 like the article type and RR labels) and its text isn't vertically centered (see screenshot below)
![Untitled-1](https://user-images.githubusercontent.com/4512335/58886135-64346700-86b1-11e9-925c-4bf4571c0892.png)

**Comment by eplebel** [comment]
looks good overall. a few minor tweaks/fixes:
1. please position the BETA text so it looks like the screenshot i provided (i think margin-left:-2px does the trick)
2. article type and RR labels now have too much extra space above them (please adjust them so they look like the specs; i think setting article type and RR labels margin-top:2px (instead of margin-top:5px as is needed for the commentaries label style) does the trick
3. "count" style font-size is now too small (it should be .55rem ; it seems to have accidentally changed to .45rem)
4. all 5 unavailable badge titles incorrectly displays: "[undefined] is not (yet) available"
5. for format_quote, please add margin-right:-3px to remove extra space between icon and actual citation count (to be consistent w/ other impact metric icons)
6. abstract trimming: please trim after 540 (instead of 550; which sometimes results in an extra line with only 1 word; my oversight)

**Comment by onejgordon** [comment]
@eplebel "count" style font-size was changed to .45em because at .55 it results in a badge that is 22.5px rather than 22px high like the badges without counts. I've spent some time tweaking this and can't seem to get around the tradeoff. Happy to continue working on it, but also cognizant of resource efficiency / constraints.

**Comment by eplebel** [comment]
thanks. 
the "count" style issue is good enough for now, so you can just leave it is as is.
the other issues are all good too, and all regression UI tests seem to be passing, so please merge to production branch, thanks.
