### ISSUE TITLE
additional minor aesthetic/UI issues

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#59]
- [x] update replication details "Original study" place holder text to "e.g., Smith (2000) Study 2" (remove "SS")
- [x] add loading spinners for figures, loading article editor, & anywhere else where there is a noticeable loading lag...
- [x] add CTRL+S keyboard shortcut to Edit Author window
	- CTRL+S bug: hitting CTRL+S on main author page and edit author modal incorrectly displays "Please enter publication year" as if it's trying to save an empty article (it doesn't always happen, but have observed it on-and-off since CTRL+S functionality was implemented)
- [x] commentaries popup incorrectly activating (only above midpoint due to an overlapping \<span> element) instead of entire label (like replication label)
- [x] transparency badge popup also incorrectly activating (only activates above midpoint of badge also due to an overlapping \<span> element)
![Untitled](https://user-images.githubusercontent.com/4512335/59612056-728b7580-90ea-11e9-935d-4cecbb8a00f6.png)
- [x] update replication label popup text: remove "(target effects:" and ")." and italicize target_effect text.   So text should be:  "Article reports [# of reps] replications of [original_study] [target_effect]" (e.g., "Article reports 2 replications of Vess (2012) Study 1 _anxious attachment warm food effect_")

**Comment by eplebel** [comment]
great, looks good. 

please also add a spinner for:
- while loading existing figures within article editor, and
- while loading new figures that are being uploaded within article editor

**Comment by onejgordon** [comment]
Will be on staging shortly

**Comment by eplebel** [comment]
great, thanks. 
(for replication article type, the spinner his hidden for a 1050px vertical viewport), but this is good enough for now.)

i've tested core functionality, please merge to production, branch, thanks!

**Comment by onejgordon** [comment]
Merged.
