### ISSUE TITLE
non-live articles not excluded on homepage article list

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#62]
homepage article list, like author page article list, needs to exclude "non-live" articles (articles being created).

basically, when a new article is created, it is set to isLive=false until it is saved, which is then set to true (see [here](https://github.com/ScienceCommons/curate_science/blob/ac80dc2f62518c1c7ed864011559a24a54dc857b/src/pages/AuthorPage.jsx#L123)) and hence only then  displayed on author page (& homepage) article lists), see here for a comment about this: https://github.com/ScienceCommons/curate_science/issues/12#issuecomment-470391630  
(relevant article model line of code: https://github.com/ScienceCommons/curate_science/blob/master/curate/models.py#L182)

![Untitled](https://user-images.githubusercontent.com/4512335/62139080-b6ab9180-b2b6-11e9-95e5-6d51fed7205a.png)

(this should probably be better explained in our documentation)

**Comment by mickaobrien** [comment]
@eplebel I just pushed a fix for this to the master branch there, that should do the job :crossed_fingers: I rebased the `staging` branch too so the fix is present there too.

I had completely missed this, so I need to filter out the non-live articles from the search results too, but I presume that's not as urgent? Should authors who aren't activated be hidden from the search results too?

**Comment by eplebel** [comment]
great, you're a savior! indeed issues seems fixed, thanks so much for quick turnaround on this!

> so I need to filter out the non-live articles from the search results too, but I presume that's not as urgent? Should authors who aren't activated be hidden from the search results too?

and yes non-live articles also need to be filtered out/excluded from search autocomplete/results *and* non-activated authors also need to be excluded from search results (but these are non-urgent).
