### ISSUE TITLE
new landing page & other content updates

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#75]
Note: All new assets can be found under `curate_science\sitestatic\infographics` (2 new icons under `curate_science\sitestatic\icons` )

**LANDING & HIW section details** (for non-logged in users; see below for details re: logged-in users)

As per this mockup (text included below mockup):
![landing-page-HIW-section](https://user-images.githubusercontent.com/4512335/68030523-1176cf80-fc90-11e9-93f3-b457f50ae403.png)
NOTE: All carousels are Material Design responsive, touch-enabled, and swipable carousels and each image is enlargeable on click via FancyBox media viewer (like this [MDbootstrap library](https://mdbootstrap.com/docs/jquery/javascript/carousel/#with-captions)). *ALL* infographics across landing, HIW, and About sections are arrayed within the same (FancyBox) set (via "data-fancybox=setNameString"), so that users can just cycle through all infographics (this will result in some duplication, but that's still better UX overall). (just like my alpha prototype, etiennelebel.com, where all key figures are arrayed within the same set ("data-fancybox=images"), so user can cycle through all key figures across all articles!)

TEXT:
**Tagline**: Transparent and credible scientific evidence.

**Are you an author?**
Be a transparent and credible researcher and accelerate your science with confidence.
**Are you a replicator?**
Add your replication to our database to increase its visibility, discoverability, and impact.
**Are you an educator?** 
Find open data sets and study materials for your courses in statistics, research methodology, or meta-science.

**HOW IT WORKS**
**FOR AUTHORS**
Communicate the transparency and credibility of your research according to recognized transparency standards on your own (externally embeddable) author page.

Organize your publications (full-text URLs, key figures, etc.) and share and disseminate your research.

Increase the discoverability, accessibility, and impact of your research, giving yourself a competitive edge in hiring/grant contexts.

Feel confident inviting the world to both use and scrutinize your work.

**FOR REPLICATORS**
Link your replication to the original study to increase its visibility, discoverability, and impact, accelerating scientific self-correction.

Curate replication metadata on its own article page and easily share it.

Create collections of replications across different methods of testing an effect, and meta-analyze and track replication evidence (coming soon).

**FOR EDUCATORS**
Find open data sets and analysis code on specific topics for your courses in statistics, research methodology, or meta-science.

Discover open study materials for course-related replication projects on topics relevant to your students' interests.

Identify transparent and credible research findings to include in your courses.

Curate the transparency and credibility of seminal findings for your graduate seminar classes, organized in article lists re-usable by other instructors (coming soon).

**ABOUT section**
Same general layout as HIW section, except MISSION & VISION stackable boxes at the top

As per this mockup (text included below mockup):
![about-page-new-oct-2019](https://user-images.githubusercontent.com/4512335/68034415-ff992a80-fc97-11e9-8510-c40671fed2ca.png)

**Mission**: Accelerate science by developing the best transparency and credibility curation tools for all research stakeholders.

**Vision**: Create an accountable research world brimming with transparent and credible evidence.

Every year, millions of people suffer and/or die from serious conditions like cancer, Alzheimer’s, heart disease, anxiety/mood disorders, and suicide. To make progress on these and other problems, funded scientific research must be, at minimum, **transparent and credible** (credible research is transparent evidence that survives scrutiny from peers). Transparent and credible evidence can then be built upon, which allows ever more precise theories/hypotheses to be tested (solid cumulative knowledge cannot be built on quicksand). Sadly, there is a growing body of credible evidence that the majority of (current) academic research is not minimally transparent nor credible ([[1](https://pdfs.semanticscholar.org/3813/c9cb1bbbf699998b622fe4c8dbb02c9db482.pdf)], [[2](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0200303)], [[3](https://www.nature.com/articles/tp2017203)], [[4](https://osf.io/preprints/metaarxiv/6uhg5/)], [[5](http://bioinformatics.sph.harvard.edu/ngs-workshops/documents/introduction/Nat%20Genet%202009%20Ioannidis.pdf)], [[6](https://www.federalreserve.gov/econresdata/feds/2015/files/2015083pap.pdf)], [[7](https://tomhardwicke.netlify.com/files/Hardwicke_reproducibility_2018.pdf)], [[8](https://psyarxiv.com/fk8vh/)], [[9](https://etiennelebel.com/documents/osc(2015,science).pdf)], [[10](https://www.nature.com/articles/nrd3439-c1)], [[11](https://www.nature.com/articles/483531a)], [[12](https://osf.io/8srcd/)], [[13](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1002165)]).
 
Curate Science is a unified curation system and platform to verify that research is **transparent and credible**. It will allow researchers, journals, universities, and funders to ensure: 
**Transparency**: Ensure research meets minimum transparency standards appropriate to the article type and employed methodologies.
**Credibility**: Ensure follow-up scrutiny is linked to its parent paper, including critical commentaries, reproducibility/robustness re-analyses, and new sample replications.
 
By ensuring **transparency and credibility**, research stakeholders are held accountable to the people/groups they serve.

**RESEARCHERS**
Researchers can ensure their publications meet minimum transparency standards via their own (externally embeddable) author page, in addition to a host of other benefits (see [HOW IT WORKS section]).

This makes researchers accountable to (1) their employer, (2) the government/taxpayer who funds their research (if publicly funded), and (3) the public, given researchers’ societal responsibility as public intellectuals.

**JOURNALS**
Journals can ensure that submitted articles meet a minimum transparency standard of their choice, and ensure that follow-up scrutiny of published papers is automatically linked within their journal issue article lists.  

This holds journals accountable to what they publish, making them accountable to (1) the research community they serve, (2) the parent professional society that owns the journal (if applicable), and (3) organizations and public officials who rely on peer-reviewed journal articles for evidence-based decision-making.

**UNIVERSITIES / RESEARCH INSTITUTES**
Universities can ensure that professors' published research meets a specific transparency standard for passing appropriate scrutiny, which can be used for promotion/hiring decisions.

University departments can then be ranked by their transparency track record, which graduate students/job candidates can use to decide at what university to work.

This makes universities accountable to their stakeholders: (1) tuition-fee paying students, (2) the government/taxpayer (for public universities), and/or (3) private/corporate donors.

**FUNDERS / FUNDING AGENCIES**
Ensure that grantees' publications meet a minimum transparency standard and survive follow-up scrutiny. 

Use researchers’/grantees’ transparency track record to inform grant selection and grant renewal decisions.

This makes funders accountable to their stakeholders: (1) the taxpayer (for government funding agencies) and/or (2) the philanthropist donors (for private/non-profit foundations).

**CURATE SCIENCE ACCOUNTABILITY**
Practising what we preach, several transparency and credibility measures have been (or will be) implemented to ensure that we are accountable to our own stakeholders that we serve: (1) our users, (2) the research community, and (3) the public:
 
**Transparency measures**
- Open-source code base, open ontologies, and open standards.
- Openly-licensed curated content, accessible via an open database/open API, which can be easily re-used/re-posted via embeddable widgets. This enables the scholarly community/users to be in full control of their curated publications/content, unlike other platforms where content is either not flexible or accessible (Google Scholar) or only accessible to logged-in users (like Academia.edu and ResearchGate, who use a lock-in model).
- Transparent logging of all user curation contributions including editors and volunteer/paid curators. All users must use their real name (and be affiliated with a research institute) and will have their own user page displaying all of their contributions/edits.
 
**Credibility measures**
- Flag issues with content (e.g., inaccuracies/discrepancies, incomplete information, broken links) from any article card/article page, even when content is embedded externally.
- Incentivize high quality information that is sensitive to the power/political dynamics in academia:
  - Communication system to allow users to anonymously request clarification from an author regarding possible limitations/errors in a published work, including revocable confidentiality of information escrow to hold each party accountable.
  - Bug bounty initiative/program that provides financial rewards to those who identify errors/limitations of published research (financial bounties provided by original author and/or outside donors).

![transparent-rectangle-box](https://user-images.githubusercontent.com/4512335/67980956-e9d32900-fbf5-11e9-876e-dfeeb35bb396.png)

**Updated NAVBAR details**: 
- Sticky navbar (just like on [replications page](https://curate-science-staging-2.appspot.com/app/replications))
- Reduce width of search box from 550px to ~400px
- Browse link (to the right of search box), which brings user to "Recent articles" section
  - *Non-logged in users*:
    - Update login button to "LOGIN" (instead of "LOGIN TO CURATE")
    - Display HOW IT WORKS (outline-less) button instead of HELP button
  - *Logged-in users*:
    - HELP visible to logged-in users only (HOW IT WORKS displayed for non-logged in users)
    - User avatar becomes a fixed author page home button & new down-caret to the right of avatar to activate user menu (as per mockup)
![navbar-logged-in](https://user-images.githubusercontent.com/4512335/67885282-af965880-fb1d-11e9-8e47-0a4f10f061e8.png)

![transparent-rectangle-box](https://user-images.githubusercontent.com/4512335/67980956-e9d32900-fbf5-11e9-876e-dfeeb35bb396.png)
**Order of sections (non-logged in vs. logged-in):**
Basically: Landing page only shown to non-logged in users; For logged-in users, the order of HIW and recent articles sections are switched around. That is:
- Non-logged in:
   - Landing, HIW, Recent articles, About, People, FAQ, Newsletter
- Logged-in:
   - Recent articles, HIW, About, People, FAQ, Newsletter

Note: All of these sections are now on the same page, for better UX, which will likely require some kind of "lazy loading" so that not everything attempts to get loaded all at once on page load; Only legacy "Replications" and "Help" pages remain as separate pages.

![transparent-rectangle-box](https://user-images.githubusercontent.com/4512335/67980956-e9d32900-fbf5-11e9-876e-dfeeb35bb396.png)
**Updated drawer links** Update text and order to:
- "How it works" (goes to HIW section)
- "Browse" (goes to Recent articles section)
- "About" (goes to About section)
- "People" (goes to People section, which is presently at the end of the [About page](https://curatescience.org/app/about))
- "FAQ" (goes to FAQ section)
- "Newsletter" (goes to Newsletter section)
- "Replications (legacy)" (goes to separate [Replications page](https://curatescience.org/app/replications))
- "Help" (goes to separate [Help page](https://curatescience.org/app/help))

![transparent-rectangle-box](https://user-images.githubusercontent.com/4512335/67894706-7b2b9800-fb2f-11e9-8e25-0c462989e163.png)

**Comment by mickaobrien** [comment]
@eplebel A few questions on the home page stuff

* Could you add the links for the buttons? I'm not sure where some of them should go
* For the small screen view, I think the position of the images in the "How It Works" sections ("For Authors" etc.) is a bit confusing. They're kind of floating between sections (after the button and before the next title). I'd move the images between the title and the explanation text. What do you think?

**Comment by eplebel** [comment]
> Could you add the links for the buttons? I'm not sure where some of them should go

for sure, here they are:
**LANDING**
- LEARN MORE: goes to HIW "FOR AUTHORS" box
- SIGN UP: goes to signup page
- BROWSE: goes to Recent articles section

**HIW**
- CREATE AUTHOR PAGE: goes to signup page
- ADD REPLICATION: goes to signup page
- BROWSE: goes to Recent articles section

> For the small screen view, I think the position of the images in the "How It Works" sections ("For Authors" etc.) is a bit confusing. They're kind of floating between sections (after the button and before the next title). I'd move the images between the title and the explanation text. What do you think?

yes, i was actually going to request that but thought it might be too tricky, so yes please! :-)

**Comment by mickaobrien** [comment]
@eplebel Quick question about the home page layout:

> Non-logged in:
>     Landing, HIW, Recent articles, About, People, FAQ, Newsletter
> Logged-in:
>     Recent articles, HIW, About, People, FAQ, Newsletter

I was working off the image mockups above and didn't realise that you wanted all the other stuff (Recent articles, About, People, FAQ, Newsletter) on the home page as well (not a huge issue, it's easy enough to move that stuff around). My only concern is that I think it might be a bit confusing to to have the 'Recent articles' component (with all its interactivity) in the middle of the page for non-logged in users. Even having all the other stuff below it for logged in users feels a bit noisy to me. I was thinking it might work better as some sort of a sample for non-logged in users (e.g. here are the latest 5 articles, no interactivity on the page but links to the individual article pages and the recent articles page if interested) and a standalone page for logged in users (like it is now).

As I say it's easy enough to move these things around (maybe a bit more work to add that standalone sample for non-logged in users), so I'm happy to do whatever you'd prefer, just thought I'd mention it.

**Comment by eplebel** [comment]
ok, to keep things simpler, let's just go with:

Non-logged-in user:
Landing, HIW, About, People, FAQ, Newsletter

Logged-in user:
Recent articles only;  but clicking on HIW, About, People, FAQ, or Newsletter from side-drawer, would load "amalgamated about page" (HIW-About-People-FAQ-Newsletter) and bring user to respective section.

does that work?

(standalone latest 5 articles for non-logged in users is a good idea, but in the name of saving you time to prioritize other items, we can tackle this later.)

**Comment by mickaobrien** [comment]
Sounds good!

**Comment by eplebel** [comment]
final minor outstanding tweaks:

- esthetic stuff:
  - [ ] add correct padding for "Are you " cards on landing page, i.e., update padding of MuiCardActions div to 0px 16px 16px 16px (from 8px all around)
  - font-size tweaks in a few different spots:
    - [ ] landing page title text: decrease font-size to 1.4rem (from1.8rem); decrease line-height to 1.3 (from 1.5)
    - [ ] decrease howItWorksDescription (classes.howItWorksDescription) text font-size to 1.125rem (from 1.25rem), in HIW, About sections, FAQ, and Newsletter

- [ ] visible next/previous arrow buttons for carousels, making sure color is grey instead of white (like [here](https://react-responsive-carousel.js.org/#install) and [here](https://codesandbox.io/s/jj9ol25629?from-embed))

- [ ] clicking HOW IT WORKS link within About section isn't correctly offset (like clicking "How it works" from drawer)
- [ ] update "Are you an author?" LEARN MORE button link to #how-it-works (instead of #for-authors)
- [ ] add full-screen icon button within fancyBox viewer

- [ ] mobile: if on the middle of a page, and then click to go to Recent or Author page, the target page doesn't correctly load at the top of the page (it first displays footer, then displays the page somewhere in the middle of the Recent or Author page).

**Comment by eplebel** [comment]
wow, thanks for the promptly addressing all of those, they all look good. 

so here are the final outstanding issues:
- [ ] i still can't see the text and links changes i made (https://github.com/ScienceCommons/curate_science/commit/e8bb085097b802298066f2ff224eb6ff442d88ca); perhaps because a bundle.js wasn't produced? 
- [ ] in Funders section of About page, the carousel needs to be removed given there's only 1 image (as per spec), w/out removing ability to view it in lightbox of course 

other remain stuff:
- [ ] remove the horizontal dividers (as per https://github.com/ScienceCommons/curate_science/commit/a18e04ae0b764619a17addf61ae8f0caa00426be#commitcomment-36231553)
- [ ] fix the bottom margin of the NEWSLETTER header (e.g., add margin-bottom 2rem?)
- [ ] the fancyBox array of images is somehow 33 images instead of 18 (as it correctly was with the react-images lightbox), and when you click on the 1st image, it's actually 2 of 33 (see screenshot, as per https://github.com/ScienceCommons/curate_science/commit/9f4c1addfa74a02f2a9f7e799221ef2be33629c3#commitcomment-36231490)
- [ ] when exiting out of fancyBox, the order of the images in the carousel one clicked into become incorrect and sometimes when returning to carousel, two halves of two images are displayed (though i haven't figured out reproducible steps for these); we can potentially live with this if it's not an easy fix, but hopefully it's an easy fix (as per https://github.com/ScienceCommons/curate_science/commit/9f4c1addfa74a02f2a9f7e799221ef2be33629c3#commitcomment-36231490)

i think that's it!  (this is looking deliciously good!)

**Comment by eplebel** [comment]
wow, you did it, looks like you've covered everything on the list! huge thanks, i'm pretty happy with it.

i'm finalizing updates to the FAQ text, but once i push that, and do the regression UI tests, we can then merge to production!


i guess for next steps, please start on #63 full-screen mode, for which we can aim for a scaled back version of (e.g., maybe only support full-text PDFs, full-text HTML content, and  update to fancyBox media viewer for key figures....)

**Comment by eplebel** [comment]
ok i'm now done updating the text in the HIW, About, and FAQ sections, and just finished all UI regression tests and didn't find any new issues.

so please go ahead and merge **all** staging commits with the master branch (unless you anticipate issues).

huge thanks again, this is only a minor release, but a large accomplishment symbolically in terms of moving forward on our 5-year plan!

**Comment by mickaobrien** [comment]
@eplebel Just merged all staging commits to master there, looks good I think. Let me know if you come across any issues.

You're welcome! Glad it's going well :smile:

**Comment by eplebel** [comment]
awesome, looks like everything is in order in production. thanks again.

and please let me know if you have any questions re: full-screen mode functionality!
