### ISSUE TITLE
2-3 second delay when returning to website after being away for 5-10 mins

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#80]
the speed/responsiveness of the website (for both production & staging) is overall pretty decent, but i've noticed that if i don't use the website for 5-10 minutes, it then takes 2-3 seconds to respond to any action (loading page, search autocomplete, etc.). i'm thinking this delay is perhaps to "wake up" the server because we're using the cheapest/free tier VM instances. (`Micro Instance with burstable CPU running in EMEA`; i'm not seeing any such option [within GCP](https://console.cloud.google.com/compute/instancesDetail/zones/europe-west1-d/instances/curatevm?project=curate-science-216207), but i'm probably not looking at the right place))

do you know if there's any way of reducing this "waking up" delay w/out using more expensive resources?? (or perhaps there are other way to improve performance for this issue).

**Comment by alexkyllo** [comment]
Ok, the change to set `min_instances = 1` is deployed (to production only, not staging) so try it out and let me know if that cold start latency goes away.

**Comment by eplebel** [comment]
awesome, i will start testing it (thanks for quick turn around on this!!)

**Comment by eplebel** [comment]
wow, i think that did it!!!
(i'm still testing a bit more, with additional/longer interval periods, but will let you know! and then we can update the configuration for the staging website, because it's also pretty annoying while testing)

**Comment by alexkyllo** [comment]
Good to hear! Though I'm not 100% sure if the 28 instance hours per day free is per-project or per billing account, though, so I don't know if you'll get charged for setting both production and staging `min_instances` to 1.

**Comment by eplebel** [comment]
based on additional testing, it definitely still seems fixed. 

though that said, the 1st time i used in the morning, it seemed to have that 3-second delay again, but i'm not 100% sure, so i'm going to have to test more (because in theory it shouldn't matter if i wait 10 minutes or 10 hours right?).

and ok, let's just keep this change in production for now, and we can consider also changing it for staging at a later time.

**Comment by eplebel** [comment]
this morning, it seemed fine (which makes more sense), so perhaps yesterday it was slower due to some other unknown reason... i'll keep testing!
