### ISSUE TITLE
~2 second latency issue on staging

### ISSUE THREAD

**Issue by eplebel** [ScienceCommons/curate_science#9]
the staging website ( https://curatescience-staging.appspot.com/ and https://curatescience-staging.appspot.com/new/recent  ) is substantially slower than the production website (https://curate-science-216207.appspot.com/). e.g., loading homepage/viewing article takes a full 3-4 seconds whereas on the production website it's almost instantaneous. 

**jeremy input**: it seems to take a good 3-4 seconds longer to load an article page (or to load an article's "update" page) compared to production, and it seems to stay this way even after several interactions (potentially ruling out Jeremy's "warm up" hypothesis).

**Alex responses**:
Testing it out, I also noticed that staging takes about 3000ms per request while prod takes only about 400ms. They're not configured any differently in App Engine, and the two databases are on the same VM, so there must be something about how the database are configured that's causing different SQL query latency. I'll keep digging...

The individual SQL statements being issued to the database are the same between prod and staging, so it is not due to any code change in the Django app generating slower queries on staging. And when I run the queries directly on the server, they take a similar amount of time on both databases. The databases have identical schemas and almost identical data in them so now I'm leaning toward it being something in GAE, but I'm not sure what yet. I basically didn't configure anything in GAE so I'm not sure what settings there are that affect app performance. That will require more research.

I can confirm that it's also not the indexes--staging has the exact same indexes as prod.

**What about just recreating *both* production and staging websites anew and seeing if that resolves the issue?**

**Comment by alexkyllo** [comment]
Recreating the GAE instance is worth a try, I suppose. Another possibility is to redeploy the whole app to the VM instead of using GAE. Should we first focus on rewriting the app for the upcoming new specs, before working on performance optimization?

**Comment by eplebel** [comment]
my reasoning is that this latency issue will still be a problem once the app is updated (to my understanding the app will simply be *updated* rather than *completely rewritten*). hence, i thought it would be more efficient time-wise to try and resolve it *while* i'm finalizing specs for the updated app/author page.

**Comment by onejgordon** [comment]
I'm still suspicious that some of the new queries that pull large batches of related entities might be influencing latency. If that's the case, this new flattened data model may resolve the problem. As such, might be more efficient to wait until the data model changes (and therefore the queries) are made before spending too much time investigating.

**Comment by alexkyllo** [comment]
This was a GAE configuration issue caused by a hardcoded port number in app.yaml that was preventing nginx from starting. Resolved by updating app.yaml and redeploying.

**Comment by eplebel** [comment]
it is now confirmed that staging has a unique ~2 seconds latency issue to post/update articles given that posting/updating articles on production (which is running on the same free tier VM) only take about .5 seconds (e.g., https://curate-science-216207.appspot.com/articles/8/).

it's important that this latency issue is addressed for (1) faster testing and also for (2) bench-marking purposes (e.g., when introducing new performance/speed-related changes on staging and we need to be able to know that performance/speed has *not* been significantly reduced).

**Comment by eplebel** [comment]
> Reopening the issue is fine, I'm thinking I will deploy another staging instance and compare performance between the two, and if it's faster, delete the slower one.

any update @alexkyllo on this attempted solution?

**Comment by alexkyllo** [comment]
I realized that curate-science-216207 (prod) is in the west-europe region while curatescience-staging is in the us-central region. This probably explains the higher latency on staging.

You can't change the region for GAE once it's created, you have to create a new project. If you want to create a new project in GCP (requires enabling billing / entering a payment method) and grant me access, I can redeploy the staging branch to it.

**Comment by eplebel** [comment]
i'm not sure about this theory because i'm pretty sure the latency issue on staging (but not production) was exactly the same when i was Canada in January/Feb.

plus, that would mean that *both of you* should be experiencing a ~2 second delay for the production website, but not staging (given you're both in the US).   @onejgordon are you seeing this on your end?

what about just duplicating/re-deploying the production website (renaming it as staging#2) to see if it gets rid of the ~2 latency (which it should given it'd be an exact copy/duplication of the current production app/website)? (does this also require me to create a new project in GCP and enable billing, etc.?)

**Comment by alexkyllo** [comment]
I think it's due to the distance between the app engine and the database. For prod both are in Belgium, but for staging the app engine is in US Central, but the database is still in Belgium. So the distance the query request and data response have to travel between staging DB and staging app engine is constant, regardless of where in the world the user is.

Creating any new app engine instance requires creating a new project and enabling billing for it. App engine is 1:1 with projects.

**Comment by eplebel** [comment]
ok thanks for the follow-up.

so i'll go ahead and create a new  project in GCP (staging #2), enable billing, and grant you access, so that you can duplicate the production app so that staging #2 has its app engine and DB both in Belgium/west-europe.
(as a side note, curious to know why we ended up w/ this difference in setup between production and staging?)

**Comment by eplebel** [comment]
ok i've just created a new GCP project called "curate-science-staging-2", enabled billing for it, and added you as owner/admin.  (so you can go ahead and **redeploy the production/master branch to it, and redeploy the production/master DB to it**)

please let me know if you need anything else from my end, thanks.

**Comment by alexkyllo** [comment]
Wait, I'm confused--why do you want me to deploy the master branch instead of the staging branch to curate-science-staging-2?

**Comment by eplebel** [comment]
well to rule out that the issue is somehow due to a configuration setting associated with the staging branch (though perhaps this is not possible...)

**Comment by alexkyllo** [comment]
Well, if I deploy staging to a GAE in west-europe and it's faster than the us-central one, that will support my region hypothesis--if not, then it supports your configuration hypothesis. Let's see!

**Comment by eplebel** [comment]
any update @alexkyllo on this?

**Comment by alexkyllo** [comment]
The second staging site is up now: https://curate-science-staging-2.appspot.com/

Let me know if it seems faster than https://curatescience-staging.appspot.com/ to you

**Comment by eplebel** [comment]
hurray!!!!!!!!!!!!!! it seems about the same as master/production branch!

(and out of curiosity, i assume `/api/articles/` for production site is also taking 400-500 ms on your end?)

**Comment by eplebel** [comment]
oh so i guess we should move/update all staging stuff to  https://curate-science-staging-2.appspot.com/
